USE HOSPITAL_DB;

### SECTION 4 — ADVANCED SQL (GROUP BY + HAVING + SUBQUERY + WINDOW) 
# Find diseases with more than two patients.
SELECT DISEASE, COUNT(*) FROM PATIENTS GROUP BY DISEASE HAVING COUNT(*) >2;

# Find treatments generating revenue above 2000.
SELECT TREATMENT, SUM(TOTAL_AMOUNT) FROM BILLING GROUP BY TREATMENT HAVING SUM(TOTAL_AMOUNT)>2000;

# Find diseases where average billing exceeds hospital average.
SELECT P.DISEASE, AVG(B.TOTAL_AMOUNT) FROM PATIENTS P JOIN BILLING B ON P.PATIENT_ID=B.PATIENT_ID GROUP BY P.DISEASE HAVING AVG(B.TOTAL_AMOUNT) > (SELECT AVG(TOTAL_AMOUNT) FROM BILLING);

# Find treatments with billing count above average billing count.
SELECT TREATMENT, COUNT(*) FROM BILLING GROUP BY TREATMENT HAVING COUNT(*) > (SELECT AVG(COUT) FROM (SELECT COUNT(*) AS COUT FROM BILLING GROUP BY TREATMENT) X );

# Find diseases with highest patient count.
SELECT DISEASE FROM PATIENTS GROUP BY DISEASE HAVING COUNT(*) = ( SELECT MAX(CNT) FROM ( SELECT COUNT(*) CNT FROM PATIENTS GROUP BY DISEASE) X);

# Find diseases with lowest patient count.
SELECT DISEASE FROM PATIENTS GROUP BY DISEASE HAVING COUNT(*) = ( SELECT MIN(CNT) FROM ( SELECT COUNT(*) CNT FROM PATIENTS GROUP BY DISEASE) X);

# Find treatments with highest revenue.
SELECT TREATMENT FROM BILLING GROUP BY TREATMENT HAVING SUM(TOTAL_AMOUNT) = ( SELECT MAX(CNT) FROM ( SELECT SUM(TOTAL_AMOUNT) CNT FROM BILLING GROUP BY TREATMENT) X);

# Find treatments with lowest revenue.
SELECT TREATMENT FROM BILLING GROUP BY TREATMENT HAVING SUM(TOTAL_AMOUNT) = ( SELECT MIN(CNT) FROM ( SELECT SUM(TOTAL_AMOUNT) CNT FROM BILLING GROUP BY TREATMENT) X);

# Find patients with billing greater than average billing.
SELECT * FROM BILLING WHERE TOTAL_AMOUNT > (SELECT AVG(TOTAL_AMOUNT) FROM BILLING);

# Find patients with billing equal to maximum billing.
SELECT * FROM BILLING WHERE TOTAL_AMOUNT > (SELECT MAX(TOTAL_AMOUNT) FROM BILLING);

# Find patients with billing equal to minimum billing.
SELECT * FROM BILLING WHERE TOTAL_AMOUNT > (SELECT MIN(TOTAL_AMOUNT) FROM BILLING);

# Find diseases whose revenue equals maximum disease revenue.
SELECT P.DISEASE FROM PATIENTS P JOIN BILLING B ON P.PATIENT_ID=B.PATIENT_ID GROUP BY P.DISEASE HAVING SUM(B.TOTAL_AMOUNT)= ( SELECT MAX(REV) FROM ( SELECT SUM(B.TOTAL_AMOUNT) REV FROM PATIENTS P JOIN BILLING B ON P.PATIENT_ID=B.PATIENT_ID GROUP BY P.DISEASE )X);

# Find diseases whose revenue equals minimum disease revenue.
SELECT P.DISEASE FROM PATIENTS P JOIN BILLING B ON P.PATIENT_ID=B.PATIENT_ID GROUP BY P.DISEASE HAVING SUM(B.TOTAL_AMOUNT)= ( SELECT MIN(REV) FROM ( SELECT SUM(B.TOTAL_AMOUNT) REV FROM PATIENTS P JOIN BILLING B ON P.PATIENT_ID=B.PATIENT_ID GROUP BY P.DISEASE )X);

# Find treatments whose revenue equals maximum treatment revenue.
SELECT P.DISEASE FROM PATIENTS P JOIN BILLING B ON P.PATIENT_ID=B.PATIENT_ID GROUP BY P.DISEASE HAVING SUM(B.TOTAL_AMOUNT)= ( SELECT MAX(REV) FROM ( SELECT SUM(B.TOTAL_AMOUNT) REV FROM PATIENTS P JOIN BILLING B ON P.PATIENT_ID=B.PATIENT_ID GROUP BY P.DISEASE )X);

# Find treatments whose revenue equals minimum treatment revenue.
SELECT P.DISEASE FROM PATIENTS P JOIN BILLING B ON P.PATIENT_ID=B.PATIENT_ID GROUP BY P.DISEASE HAVING SUM(B.TOTAL_AMOUNT)= ( SELECT MIN(REV) FROM ( SELECT SUM(B.TOTAL_AMOUNT) REV FROM PATIENTS P JOIN BILLING B ON P.PATIENT_ID=B.PATIENT_ID GROUP BY P.DISEASE )X);

# Rank patients by billing amount.
SELECT PATIENT_ID,TOTAL_AMOUNT, RANK() OVER(ORDER BY TOTAL_AMOUNT DESC) FROM BILLING;

# Rank patients by doctor fee.
SELECT PATIENT_ID, DOCTOR_FEE, RANK() OVER(ORDER BY DOCTOR_FEE DESC) FROM BILLING;

# Rank patients by medicine cost.
SELECT PATIENT_ID, MEDICINE_COST, RANK() OVER(ORDER BY MEDICINE_COST DESC) FROM BILLING;

# Rank diseases by revenue.
SELECT P.DISEASE, SUM(B.TOTAL_AMOUNT), RANK() OVER(ORDER BY SUM(B.TOTAL_AMOUNT) DESC) FROM PATIENTS P JOIN BILLING B ON P.PATIENT_ID=B.PATIENT_ID GROUP BY P.DISEASE;

# Rank treatments by revenue.
SELECT B.TREATMENT, SUM(B.TOTAL_AMOUNT), RANK() OVER(ORDER BY SUM(B.TOTAL_AMOUNT) DESC) FROM PATIENTS P JOIN BILLING B ON P.PATIENT_ID=B.PATIENT_ID GROUP BY B.TREATMENT;

# Find top patient per disease using ROW_NUMBER().
SELECT * FROM ( SELECT P.NAME,P.DISEASE,B.TOTAL_AMOUNT, ROW_NUMBER() OVER(PARTITION BY P.DISEASE ORDER BY B.TOTAL_AMOUNT DESC) RN FROM PATIENTS P JOIN BILLING B ON P.PATIENT_ID=B.PATIENT_ID ) X WHERE RN=1;

# Find top treatment per disease using RANK().
SELECT * FROM ( SELECT B.TREATMENT,P.DISEASE,B.TOTAL_AMOUNT, RANK() OVER(PARTITION BY B.TREATMENT ORDER BY B.TOTAL_AMOUNT DESC) RN FROM PATIENTS P JOIN BILLING B ON P.PATIENT_ID=B.PATIENT_ID ) X WHERE RN=1;

# Find second highest bill per disease.
SELECT * FROM ( SELECT P.DISEASE,B.TOTAL_AMOUNT, DENSE_RANK() OVER(PARTITION BY P.DISEASE ORDER BY B.TOTAL_AMOUNT DESC) R FROM PATIENTS P JOIN BILLING B ON P.PATIENT_ID=B.PATIENT_ID )X WHERE R=2;

# Find third highest bill per disease.
SELECT * FROM ( SELECT P.DISEASE,B.TOTAL_AMOUNT, DENSE_RANK() OVER(PARTITION BY P.DISEASE ORDER BY B.TOTAL_AMOUNT DESC) R FROM PATIENTS P JOIN BILLING B ON P.PATIENT_ID=B.PATIENT_ID )X WHERE R=3;

# Calculate running revenue.
SELECT BILL_ID, TOTAL_AMOUNT, SUM(TOTAL_AMOUNT) OVER(ORDER BY BILL_ID) FROM BILLING;

# Calculate cumulative revenue by treatment.
SELECT TREATMENT, SUM(TOTAL_AMOUNT) OVER(PARTITION BY TREATMENT ORDER BY BILL_ID) FROM BILLING;

# Calculate cumulative revenue by disease.
SELECT TOTAL_AMOUNT, TOTAL_AMOUNT-(SELECT AVG(TOTAL_AMOUNT) FROM BILLING) FROM BILLING;

# Find billing difference from average billing.

# Find billing difference from disease average.
# Calculate billing percentage contribution.
SELECT BILL_ID, TOTAL_AMOUNT*100/(SELECT SUM(TOTAL_AMOUNT) FROM BILLING) FROM BILLING;

# Calculate percentage revenue per disease.
SELECT P.DISEASE, SUM(B.TOTAL_AMOUNT)*100/(SELECT SUM(TOTAL_AMOUNT) FROM BILLING) FROM PATIENTS P JOIN BILLING B ON P.PATIENT_ID=B.PATIENT_ID GROUP BY P.DISEASE;

# Calculate percentage revenue per treatment.
SELECT TREATMENT, SUM(TOTAL_AMOUNT)*100/(SELECT SUM(TOTAL_AMOUNT) FROM BILLING) AS PERCENTAGE_REVENUE FROM BILLING GROUP BY TREATMENT;

# Find patients contributing highest revenue share.
SELECT P.NAME FROM PATIENTS P JOIN BILLING B ON P.PATIENT_ID=B.PATIENT_ID GROUP BY P.PATIENT_ID, P.NAME HAVING SUM(B.TOTAL_AMOUNT) = (SELECT MAX(REV) FROM (SELECT SUM(TOTAL_AMOUNT) REV FROM BILLING GROUP BY PATIENT_ID) X);

# Find treatments contributing highest revenue share.
SELECT TREATMENT FROM BILLING GROUP BY TREATMENT HAVING SUM(TOTAL_AMOUNT) = (SELECT MAX(REV) FROM (SELECT SUM(TOTAL_AMOUNT) REV FROM BILLING GROUP BY TREATMENT) X);

# Find diseases contributing highest revenue share.
SELECT P.DISEASE FROM PATIENTS P JOIN BILLING B ON P.PATIENT_ID=B.PATIENT_ID GROUP BY P.DISEASE HAVING SUM(B.TOTAL_AMOUNT) = (SELECT MAX(REV) FROM (SELECT SUM(B.TOTAL_AMOUNT) REV FROM PATIENTS P JOIN BILLING B ON P.PATIENT_ID=B.PATIENT_ID GROUP BY P.DISEASE) X);

# Find patients above disease average billing.
SELECT NAME, DISEASE, TOTAL_AMOUNT FROM (SELECT P.NAME, P.DISEASE, B.TOTAL_AMOUNT, AVG(B.TOTAL_AMOUNT) OVER(PARTITION BY P.DISEASE) AS AVG_BILL FROM PATIENTS P JOIN BILLING B ON P.PATIENT_ID=B.PATIENT_ID) X WHERE TOTAL_AMOUNT > AVG_BILL;

# Find patients below disease average billing.
SELECT NAME, DISEASE, TOTAL_AMOUNT FROM (SELECT P.NAME, P.DISEASE, B.TOTAL_AMOUNT, AVG(B.TOTAL_AMOUNT) OVER(PARTITION BY P.DISEASE) AS AVG_BILL FROM PATIENTS P JOIN BILLING B ON P.PATIENT_ID=B.PATIENT_ID) X WHERE TOTAL_AMOUNT < AVG_BILL;

# Find treatments above hospital average revenue.
SELECT TREATMENT, SUM(TOTAL_AMOUNT) FROM BILLING GROUP BY TREATMENT HAVING SUM(TOTAL_AMOUNT) > (SELECT AVG(REV) FROM (SELECT SUM(TOTAL_AMOUNT) REV FROM BILLING GROUP BY TREATMENT) X);

# Find diseases above hospital average revenue.
SELECT P.DISEASE, SUM(B.TOTAL_AMOUNT) FROM PATIENTS P JOIN BILLING B ON P.PATIENT_ID=B.PATIENT_ID GROUP BY P.DISEASE HAVING SUM(B.TOTAL_AMOUNT) > (SELECT AVG(REV) FROM (SELECT SUM(B.TOTAL_AMOUNT) REV FROM PATIENTS P JOIN BILLING B ON P.PATIENT_ID=B.PATIENT_ID GROUP BY P.DISEASE) X);

# Find patients whose billing exceeds treatment average.
SELECT NAME, TREATMENT, TOTAL_AMOUNT FROM (SELECT P.NAME, B.TREATMENT, B.TOTAL_AMOUNT, AVG(B.TOTAL_AMOUNT) OVER(PARTITION BY B.TREATMENT) AS AVG_TRT FROM PATIENTS P JOIN BILLING B ON P.PATIENT_ID=B.PATIENT_ID) X WHERE TOTAL_AMOUNT > AVG_TRT;

# Find patients whose billing is below treatment average.
SELECT NAME, TREATMENT, TOTAL_AMOUNT FROM (SELECT P.NAME, B.TREATMENT, B.TOTAL_AMOUNT, AVG(B.TOTAL_AMOUNT) OVER(PARTITION BY B.TREATMENT) AS AVG_TRT FROM PATIENTS P JOIN BILLING B ON P.PATIENT_ID=B.PATIENT_ID) X WHERE TOTAL_AMOUNT < AVG_TRT;

# Find diseases whose billing count exceeds hospital average billing count.
SELECT P.DISEASE, COUNT(*) FROM PATIENTS P JOIN BILLING B ON P.PATIENT_ID=B.PATIENT_ID GROUP BY P.DISEASE HAVING COUNT(*) > (SELECT AVG(CNT) FROM (SELECT COUNT(*) AS CNT FROM PATIENTS P JOIN BILLING B ON P.PATIENT_ID=B.PATIENT_ID GROUP BY P.DISEASE) X);

# Find treatments whose billing count exceeds hospital average billing count.
SELECT TREATMENT, COUNT(*) FROM BILLING GROUP BY TREATMENT HAVING COUNT(*) > (SELECT AVG(CNT) FROM (SELECT COUNT(*) AS CNT FROM BILLING GROUP BY TREATMENT) X);

# Find diseases whose revenue exceeds treatment revenue of Fever.
SELECT P.DISEASE, SUM(B.TOTAL_AMOUNT) FROM PATIENTS P JOIN BILLING B ON P.PATIENT_ID=B.PATIENT_ID GROUP BY P.DISEASE HAVING SUM(B.TOTAL_AMOUNT) > (SELECT SUM(B.TOTAL_AMOUNT) FROM PATIENTS P JOIN BILLING B ON P.PATIENT_ID=B.PATIENT_ID WHERE P.DISEASE='Fever');

# Find treatments whose revenue exceeds treatment revenue of Cold.
SELECT TREATMENT, SUM(TOTAL_AMOUNT) FROM BILLING GROUP BY TREATMENT HAVING SUM(TOTAL_AMOUNT) > (SELECT SUM(B.TOTAL_AMOUNT) FROM PATIENTS P JOIN BILLING B ON P.PATIENT_ID=B.PATIENT_ID WHERE P.DISEASE='Cold');

# Find diseases with patient count greater than median count.
WITH DiseaseCounts AS (SELECT P.DISEASE, COUNT(B.PATIENT_ID) AS CNT FROM PATIENTS P JOIN BILLING B ON P.PATIENT_ID=B.PATIENT_ID GROUP BY P.DISEASE), RankedCounts AS (SELECT CNT, ROW_NUMBER() OVER(ORDER BY CNT) as RN, COUNT(*) OVER() as TOTAL FROM DiseaseCounts), MedianCount AS (SELECT AVG(CNT) AS Median FROM RankedCounts WHERE RN IN (FLOOR((TOTAL+1)/2), CEIL((TOTAL+1)/2))) SELECT DISEASE, CNT FROM DiseaseCounts WHERE CNT > (SELECT Median FROM MedianCount);

# Find treatments with revenue greater than median revenue.
WITH TreatRev AS (SELECT TREATMENT, SUM(TOTAL_AMOUNT) AS REV FROM BILLING GROUP BY TREATMENT), RankedRev AS (SELECT REV, ROW_NUMBER() OVER(ORDER BY REV) RN, COUNT(*) OVER() TOTAL FROM TreatRev), MedianRev AS (SELECT AVG(REV) AS Median FROM RankedRev WHERE RN IN (FLOOR((TOTAL+1)/2), CEIL((TOTAL+1)/2))) SELECT TREATMENT, REV FROM TreatRev WHERE REV > (SELECT Median FROM MedianRev);

# Rank treatments within diseases.
SELECT P.DISEASE, B.TREATMENT, SUM(B.TOTAL_AMOUNT), RANK() OVER(PARTITION BY P.DISEASE ORDER BY SUM(B.TOTAL_AMOUNT) DESC) FROM PATIENTS P JOIN BILLING B ON P.PATIENT_ID=B.PATIENT_ID GROUP BY P.DISEASE, B.TREATMENT;

# Rank patients within diseases.
SELECT P.DISEASE, P.NAME, B.TOTAL_AMOUNT, RANK() OVER(PARTITION BY P.DISEASE ORDER BY B.TOTAL_AMOUNT DESC) FROM PATIENTS P JOIN BILLING B ON P.PATIENT_ID=B.PATIENT_ID;

# Rank diseases within gender.
SELECT P.GENDER, P.DISEASE, SUM(B.TOTAL_AMOUNT), RANK() OVER(PARTITION BY P.GENDER ORDER BY SUM(B.TOTAL_AMOUNT) DESC) FROM PATIENTS P JOIN BILLING B ON P.PATIENT_ID=B.PATIENT_ID GROUP BY P.GENDER, P.DISEASE;

# Find cumulative patient count per disease.
SELECT DISEASE, PATIENT_ID, COUNT(PATIENT_ID) OVER(PARTITION BY DISEASE ORDER BY PATIENT_ID) AS CUMULATIVE_COUNT FROM PATIENTS;

# Find cumulative billing per disease.
SELECT P.DISEASE, B.BILL_ID, B.TOTAL_AMOUNT, SUM(B.TOTAL_AMOUNT) OVER(PARTITION BY P.DISEASE ORDER BY B.BILL_ID) AS CUMULATIVE_BILLING FROM PATIENTS P JOIN BILLING B ON P.PATIENT_ID=B.PATIENT_ID;

# Find cumulative billing per treatment.
SELECT TREATMENT, BILL_ID, TOTAL_AMOUNT, SUM(TOTAL_AMOUNT) OVER(PARTITION BY TREATMENT ORDER BY BILL_ID) AS CUMULATIVE_BILLING FROM BILLING;

# Find running average billing.
SELECT BILL_ID, TOTAL_AMOUNT, AVG(TOTAL_AMOUNT) OVER(ORDER BY BILL_ID) AS RUNNING_AVG_BILLING FROM BILLING;

# Find running average medicine cost.
SELECT BILL_ID, MEDICINE_COST, AVG(MEDICINE_COST) OVER(ORDER BY BILL_ID) AS RUNNING_AVG_MEDICINE FROM BILLING;

# Find running average doctor fee.
SELECT BILL_ID, DOCTOR_FEE, AVG(DOCTOR_FEE) OVER(ORDER BY BILL_ID) AS RUNNING_AVG_DOCTOR FROM BILLING;

# Find patients whose billing exceeds running average.
SELECT NAME, TOTAL_AMOUNT, RUNNING_AVG FROM (SELECT P.NAME, B.TOTAL_AMOUNT, AVG(B.TOTAL_AMOUNT) OVER(ORDER BY B.BILL_ID) AS RUNNING_AVG FROM PATIENTS P JOIN BILLING B ON P.PATIENT_ID=B.PATIENT_ID) X WHERE TOTAL_AMOUNT > RUNNING_AVG;

# Find treatments whose revenue exceeds running average.
SELECT TREATMENT, TOTAL_AMOUNT, RUNNING_AVG FROM (SELECT TREATMENT, TOTAL_AMOUNT, AVG(TOTAL_AMOUNT) OVER(ORDER BY BILL_ID) AS RUNNING_AVG FROM BILLING) X WHERE TOTAL_AMOUNT > RUNNING_AVG;

# Find diseases whose revenue exceeds running average.
SELECT DISEASE, TOTAL_AMOUNT, RUNNING_AVG FROM (SELECT P.DISEASE, B.TOTAL_AMOUNT, AVG(B.TOTAL_AMOUNT) OVER(ORDER BY B.BILL_ID) AS RUNNING_AVG FROM PATIENTS P JOIN BILLING B ON P.PATIENT_ID=B.PATIENT_ID) X WHERE TOTAL_AMOUNT > RUNNING_AVG;

# Find revenue difference from previous billing.
SELECT BILL_ID, TOTAL_AMOUNT, TOTAL_AMOUNT - LAG(TOTAL_AMOUNT) OVER(ORDER BY BILL_ID) AS DIFFERENCE_FROM_PREVIOUS FROM BILLING;

# Find revenue difference from next billing.
SELECT BILL_ID, TOTAL_AMOUNT, TOTAL_AMOUNT - LEAD(TOTAL_AMOUNT) OVER(ORDER BY BILL_ID) AS DIFFERENCE_FROM_NEXT FROM BILLING;

# Find billing gap between consecutive bills.
SELECT BILL_ID, ABS(TOTAL_AMOUNT - LAG(TOTAL_AMOUNT) OVER(ORDER BY BILL_ID)) AS BILLING_GAP FROM BILLING;

# Find treatment revenue growth.
SELECT TREATMENT, BILL_ID, TOTAL_AMOUNT, TOTAL_AMOUNT - LAG(TOTAL_AMOUNT) OVER(PARTITION BY TREATMENT ORDER BY BILL_ID) AS REVENUE_GROWTH FROM BILLING;

# Find revenue change from previous treatment.
SELECT BILL_ID, TREATMENT, TOTAL_AMOUNT, TOTAL_AMOUNT - LAG(TOTAL_AMOUNT) OVER(ORDER BY BILL_ID) AS REVENUE_CHANGE FROM BILLING;

# Find patient billing growth.
SELECT PATIENT_ID, TOTAL_AMOUNT, TOTAL_AMOUNT - LAG(TOTAL_AMOUNT) OVER(ORDER BY PATIENT_ID) AS BILLING_GROWTH FROM BILLING;

# Find disease revenue growth.
WITH DiseaseRev AS (SELECT P.DISEASE, SUM(B.TOTAL_AMOUNT) AS REV FROM PATIENTS P JOIN BILLING B ON P.PATIENT_ID=B.PATIENT_ID GROUP BY P.DISEASE) SELECT DISEASE, REV, REV - LAG(REV) OVER(ORDER BY REV) AS GROWTH FROM DiseaseRev;

# Find treatments with increasing revenue trend.
SELECT BILL_ID, TREATMENT, TOTAL_AMOUNT FROM (SELECT BILL_ID, TREATMENT, TOTAL_AMOUNT, LAG(TOTAL_AMOUNT) OVER(ORDER BY BILL_ID) AS PREV_AMOUNT FROM BILLING) X WHERE TOTAL_AMOUNT > PREV_AMOUNT AND PREV_AMOUNT IS NOT NULL;

# Find treatments with decreasing revenue trend.
SELECT BILL_ID, TREATMENT, TOTAL_AMOUNT FROM (SELECT BILL_ID, TREATMENT, TOTAL_AMOUNT, LAG(TOTAL_AMOUNT) OVER(ORDER BY BILL_ID) AS PREV_AMOUNT FROM BILLING) X WHERE TOTAL_AMOUNT < PREV_AMOUNT AND PREV_AMOUNT IS NOT NULL;

# Find patients with increasing billing trend.
SELECT BILL_ID, PATIENT_ID, TOTAL_AMOUNT FROM (SELECT BILL_ID, PATIENT_ID, TOTAL_AMOUNT, LAG(TOTAL_AMOUNT) OVER(ORDER BY BILL_ID) AS PREV_AMOUNT FROM BILLING) X WHERE TOTAL_AMOUNT > PREV_AMOUNT AND PREV_AMOUNT IS NOT NULL;

# Find patients with decreasing billing trend.
SELECT BILL_ID, PATIENT_ID, TOTAL_AMOUNT FROM (SELECT BILL_ID, PATIENT_ID, TOTAL_AMOUNT, LAG(TOTAL_AMOUNT) OVER(ORDER BY BILL_ID) AS PREV_AMOUNT FROM BILLING) X WHERE TOTAL_AMOUNT < PREV_AMOUNT AND PREV_AMOUNT IS NOT NULL;

# Find patients with revenue above 90th percentile.
WITH Percentiles AS (SELECT PATIENT_ID, TOTAL_AMOUNT, PERCENT_RANK() OVER(ORDER BY TOTAL_AMOUNT) AS PCT FROM BILLING) SELECT PATIENT_ID, TOTAL_AMOUNT FROM Percentiles WHERE PCT >= 0.9;

# Find treatments above 90th percentile revenue.
WITH TreatRev AS (SELECT TREATMENT, SUM(TOTAL_AMOUNT) AS REV FROM BILLING GROUP BY TREATMENT), Percentiles AS (SELECT TREATMENT, REV, PERCENT_RANK() OVER(ORDER BY REV) AS PCT FROM TreatRev) SELECT TREATMENT, REV FROM Percentiles WHERE PCT >= 0.9;

# Find diseases above 90th percentile revenue.
WITH DiseaseRev AS (SELECT P.DISEASE, SUM(B.TOTAL_AMOUNT) AS REV FROM PATIENTS P JOIN BILLING B ON P.PATIENT_ID=B.PATIENT_ID GROUP BY P.DISEASE), Percentiles AS (SELECT DISEASE, REV, PERCENT_RANK() OVER(ORDER BY REV) AS PCT FROM DiseaseRev) SELECT DISEASE, REV FROM Percentiles WHERE PCT >= 0.9;

# Find patients below 10th percentile revenue.
WITH Percentiles AS (SELECT PATIENT_ID, TOTAL_AMOUNT, PERCENT_RANK() OVER(ORDER BY TOTAL_AMOUNT) AS PCT FROM BILLING) SELECT PATIENT_ID, TOTAL_AMOUNT FROM Percentiles WHERE PCT <= 0.1;

# Find treatments below 10th percentile revenue.
WITH TreatRev AS (SELECT TREATMENT, SUM(TOTAL_AMOUNT) AS REV FROM BILLING GROUP BY TREATMENT), Percentiles AS (SELECT TREATMENT, REV, PERCENT_RANK() OVER(ORDER BY REV) AS PCT FROM TreatRev) SELECT TREATMENT, REV FROM Percentiles WHERE PCT <= 0.1;

# Find diseases below 10th percentile revenue.
WITH DiseaseRev AS (SELECT P.DISEASE, SUM(B.TOTAL_AMOUNT) AS REV FROM PATIENTS P JOIN BILLING B ON P.PATIENT_ID=B.PATIENT_ID GROUP BY P.DISEASE), Percentiles AS (SELECT DISEASE, REV, PERCENT_RANK() OVER(ORDER BY REV) AS PCT FROM DiseaseRev) SELECT DISEASE, REV FROM Percentiles WHERE PCT <= 0.1;

# Find median billing per treatment.
WITH Ranked AS (SELECT TREATMENT, TOTAL_AMOUNT, ROW_NUMBER() OVER(PARTITION BY TREATMENT ORDER BY TOTAL_AMOUNT) AS RN, COUNT(*) OVER(PARTITION BY TREATMENT) AS TOTAL FROM BILLING) SELECT TREATMENT, AVG(TOTAL_AMOUNT) AS MEDIAN FROM Ranked WHERE RN IN (FLOOR((TOTAL+1)/2), CEIL((TOTAL+1)/2)) GROUP BY TREATMENT;

# Find median billing per disease.
WITH Ranked AS (SELECT P.DISEASE, B.TOTAL_AMOUNT, ROW_NUMBER() OVER(PARTITION BY P.DISEASE ORDER BY B.TOTAL_AMOUNT) AS RN, COUNT(*) OVER(PARTITION BY P.DISEASE) AS TOTAL FROM PATIENTS P JOIN BILLING B ON P.PATIENT_ID=B.PATIENT_ID) SELECT DISEASE, AVG(TOTAL_AMOUNT) AS MEDIAN FROM Ranked WHERE RN IN (FLOOR((TOTAL+1)/2), CEIL((TOTAL+1)/2)) GROUP BY DISEASE;

# Find median billing per patient.
WITH Ranked AS (SELECT PATIENT_ID, TOTAL_AMOUNT, ROW_NUMBER() OVER(PARTITION BY PATIENT_ID ORDER BY TOTAL_AMOUNT) AS RN, COUNT(*) OVER(PARTITION BY PATIENT_ID) AS TOTAL FROM BILLING) SELECT PATIENT_ID, AVG(TOTAL_AMOUNT) AS MEDIAN FROM Ranked WHERE RN IN (FLOOR((TOTAL+1)/2), CEIL((TOTAL+1)/2)) GROUP BY PATIENT_ID;

# Find median billing across hospital.
WITH Ranked AS (SELECT TOTAL_AMOUNT, ROW_NUMBER() OVER(ORDER BY TOTAL_AMOUNT) AS RN, COUNT(*) OVER() AS TOTAL FROM BILLING) SELECT AVG(TOTAL_AMOUNT) AS MEDIAN FROM Ranked WHERE RN IN (FLOOR((TOTAL+1)/2), CEIL((TOTAL+1)/2));

# Find treatments above median revenue.
WITH TreatRev AS (SELECT TREATMENT, SUM(TOTAL_AMOUNT) AS REV FROM BILLING GROUP BY TREATMENT), Ranked AS (SELECT REV, ROW_NUMBER() OVER(ORDER BY REV) AS RN, COUNT(*) OVER() AS TOTAL FROM TreatRev), MedianCTE AS (SELECT AVG(REV) AS Median FROM Ranked WHERE RN IN (FLOOR((TOTAL+1)/2), CEIL((TOTAL+1)/2))) SELECT TREATMENT, REV FROM TreatRev WHERE REV > (SELECT Median FROM MedianCTE);

# Find diseases above median revenue.
WITH DiseaseRev AS (SELECT P.DISEASE, SUM(B.TOTAL_AMOUNT) AS REV FROM PATIENTS P JOIN BILLING B ON P.PATIENT_ID=B.PATIENT_ID GROUP BY P.DISEASE), Ranked AS (SELECT REV, ROW_NUMBER() OVER(ORDER BY REV) AS RN, COUNT(*) OVER() AS TOTAL FROM DiseaseRev), MedianCTE AS (SELECT AVG(REV) AS Median FROM Ranked WHERE RN IN (FLOOR((TOTAL+1)/2), CEIL((TOTAL+1)/2))) SELECT DISEASE, REV FROM DiseaseRev WHERE REV > (SELECT Median FROM MedianCTE);

# Find patients above median billing.
WITH Ranked AS (SELECT TOTAL_AMOUNT, ROW_NUMBER() OVER(ORDER BY TOTAL_AMOUNT) AS RN, COUNT(*) OVER() AS TOTAL FROM BILLING), MedianCTE AS (SELECT AVG(TOTAL_AMOUNT) AS Median FROM Ranked WHERE RN IN (FLOOR((TOTAL+1)/2), CEIL((TOTAL+1)/2))) SELECT PATIENT_ID, TOTAL_AMOUNT FROM BILLING WHERE TOTAL_AMOUNT > (SELECT Median FROM MedianCTE);

# Find treatments below median revenue.
WITH TreatRev AS (SELECT TREATMENT, SUM(TOTAL_AMOUNT) AS REV FROM BILLING GROUP BY TREATMENT), Ranked AS (SELECT REV, ROW_NUMBER() OVER(ORDER BY REV) AS RN, COUNT(*) OVER() AS TOTAL FROM TreatRev), MedianCTE AS (SELECT AVG(REV) AS Median FROM Ranked WHERE RN IN (FLOOR((TOTAL+1)/2), CEIL((TOTAL+1)/2))) SELECT TREATMENT, REV FROM TreatRev WHERE REV < (SELECT Median FROM MedianCTE);

# Find diseases below median revenue.
WITH DiseaseRev AS (SELECT P.DISEASE, SUM(B.TOTAL_AMOUNT) AS REV FROM PATIENTS P JOIN BILLING B ON P.PATIENT_ID=B.PATIENT_ID GROUP BY P.DISEASE), Ranked AS (SELECT REV, ROW_NUMBER() OVER(ORDER BY REV) AS RN, COUNT(*) OVER() AS TOTAL FROM DiseaseRev), MedianCTE AS (SELECT AVG(REV) AS Median FROM Ranked WHERE RN IN (FLOOR((TOTAL+1)/2), CEIL((TOTAL+1)/2))) SELECT DISEASE, REV FROM DiseaseRev WHERE REV < (SELECT Median FROM MedianCTE);

# Find top 10% revenue generating treatments.
WITH TreatRev AS (SELECT TREATMENT, SUM(TOTAL_AMOUNT) AS REV FROM BILLING GROUP BY TREATMENT), Percentiles AS (SELECT TREATMENT, REV, PERCENT_RANK() OVER(ORDER BY REV DESC) AS PCT FROM TreatRev) SELECT TREATMENT, REV FROM Percentiles WHERE PCT <= 0.1;

# Find top 10% revenue generating patients.
WITH PatRev AS (SELECT PATIENT_ID, SUM(TOTAL_AMOUNT) AS REV FROM BILLING GROUP BY PATIENT_ID), Percentiles AS (SELECT PATIENT_ID, REV, PERCENT_RANK() OVER(ORDER BY REV DESC) AS PCT FROM PatRev) SELECT PATIENT_ID, REV FROM Percentiles WHERE PCT <= 0.1;

# Find top 10% revenue generating diseases.
WITH DiseaseRev AS (SELECT P.DISEASE, SUM(B.TOTAL_AMOUNT) AS REV FROM PATIENTS P JOIN BILLING B ON P.PATIENT_ID=B.PATIENT_ID GROUP BY P.DISEASE), Percentiles AS (SELECT DISEASE, REV, PERCENT_RANK() OVER(ORDER BY REV DESC) AS PCT FROM DiseaseRev) SELECT DISEASE, REV FROM Percentiles WHERE PCT <= 0.1;

# Find bottom 10% revenue generating treatments.
WITH TreatRev AS (SELECT TREATMENT, SUM(TOTAL_AMOUNT) AS REV FROM BILLING GROUP BY TREATMENT), Percentiles AS (SELECT TREATMENT, REV, PERCENT_RANK() OVER(ORDER BY REV ASC) AS PCT FROM TreatRev) SELECT TREATMENT, REV FROM Percentiles WHERE PCT <= 0.1;

# Find bottom 10% revenue generating patients.
WITH PatRev AS (SELECT PATIENT_ID, SUM(TOTAL_AMOUNT) AS REV FROM BILLING GROUP BY PATIENT_ID), Percentiles AS (SELECT PATIENT_ID, REV, PERCENT_RANK() OVER(ORDER BY REV ASC) AS PCT FROM PatRev) SELECT PATIENT_ID, REV FROM Percentiles WHERE PCT <= 0.1;

# Find bottom 10% revenue generating diseases.
WITH DiseaseRev AS (SELECT P.DISEASE, SUM(B.TOTAL_AMOUNT) AS REV FROM PATIENTS P JOIN BILLING B ON P.PATIENT_ID=B.PATIENT_ID GROUP BY P.DISEASE), Percentiles AS (SELECT DISEASE, REV, PERCENT_RANK() OVER(ORDER BY REV ASC) AS PCT FROM DiseaseRev) SELECT DISEASE, REV FROM Percentiles WHERE PCT <= 0.1;

# Find patient revenue percentile rank.
SELECT PATIENT_ID, TOTAL_AMOUNT, PERCENT_RANK() OVER(ORDER BY TOTAL_AMOUNT) AS PERCENTILE_RANK FROM BILLING;

# Find treatment revenue percentile rank.
WITH TreatRev AS (SELECT TREATMENT, SUM(TOTAL_AMOUNT) AS REV FROM BILLING GROUP BY TREATMENT) SELECT TREATMENT, REV, PERCENT_RANK() OVER(ORDER BY REV) AS PERCENTILE_RANK FROM TreatRev;

# Find disease revenue percentile rank.
WITH DiseaseRev AS (SELECT P.DISEASE, SUM(B.TOTAL_AMOUNT) AS REV FROM PATIENTS P JOIN BILLING B ON P.PATIENT_ID=B.PATIENT_ID GROUP BY P.DISEASE) SELECT DISEASE, REV, PERCENT_RANK() OVER(ORDER BY REV) AS PERCENTILE_RANK FROM DiseaseRev;

# Find revenue distribution.
SELECT FLOOR(TOTAL_AMOUNT/500)*500 AS RANGE_START, COUNT(*) AS COUNT FROM BILLING GROUP BY FLOOR(TOTAL_AMOUNT/500)*500 ORDER BY RANGE_START;

# Find revenue quartiles.
SELECT BILL_ID, TOTAL_AMOUNT, NTILE(4) OVER(ORDER BY TOTAL_AMOUNT) AS QUARTILE FROM BILLING;

# Find revenue variance across treatments.
SELECT VAR_POP(REV) AS VARIANCE_ACROSS_TREATMENTS FROM (SELECT TREATMENT, SUM(TOTAL_AMOUNT) AS REV FROM BILLING GROUP BY TREATMENT) X;

# Find revenue variance across diseases.
SELECT VAR_POP(REV) AS VARIANCE_ACROSS_DISEASES FROM (SELECT P.DISEASE, SUM(B.TOTAL_AMOUNT) AS REV FROM PATIENTS P JOIN BILLING B ON P.PATIENT_ID=B.PATIENT_ID GROUP BY P.DISEASE) X;

# Find revenue variance across patients.
SELECT VAR_POP(TOTAL_AMOUNT) AS VARIANCE_ACROSS_PATIENTS FROM BILLING;

# Find overall hospital revenue ranking.
SELECT BILL_ID, TOTAL_AMOUNT, RANK() OVER(ORDER BY TOTAL_AMOUNT DESC) AS REVENUE_RANK FROM BILLING;
