USE hospital_db;

## SECTION 2 — BILLING ANALYSIS 

# Find total hospital revenue.
SELECT SUM(TOTAL_AMOUNT) FROM BILLING;
 
# Find average billing amount.
SELECT ROUND(AVG(TOTAL_AMOUNT)) FROM BILLING;

# Find highest billing amount.
SELECT MAX(TOTAL_AMOUNT) FROM BILLING;

# Find lowest billing amount.
SELECT MIN(TOTAL_AMOUNT) FROM BILLING;

# Count billing records.
SELECT COUNT(*) FROM BILLING;

# Find treatments generating total revenue.
SELECT TREATMENT, SUM(TOTAL_AMOUNT) FROM BILLING GROUP BY TREATMENT;

# Find treatments generating highest revenue.
SELECT TREATMENT, MAX(TOTAL_AMOUNT) FROM BILLING GROUP BY TREATMENT;

# Find treatments generating lowest revenue.
SELECT TREATMENT, MIN(TOTAL_AMOUNT) FROM BILLING GROUP BY TREATMENT;

# Find treatments performed most frequently.
SELECT TREATMENT, COUNT(*) AS MOST_FREQUENTLY FROM BILLING GROUP BY TREATMENT ORDER BY COUNT(*) DESC LIMIT 1;

# Find treatments performed least frequently.
SELECT TREATMENT, COUNT(*) AS LEAST_FREQUENTLY FROM BILLING GROUP BY TREATMENT ORDER BY COUNT(*) ASC LIMIT 1;

# Find treatments where average bill exceeds 1000.
SELECT TREATMENT, AVG(TOTAL_AMOUNT) AS AVG_BILL FROM BILLING GROUP BY TREATMENT HAVING AVG(TOTAL_AMOUNT)>1000;

# Find treatments where total revenue exceeds 2000.
SELECT TREATMENT, SUM(TOTAL_AMOUNT) AS TOTAL_BILL FROM BILLING GROUP BY TREATMENT HAVING SUM(TOTAL_AMOUNT)>1000;

# Find treatments where billing count exceeds 2.
SELECT TREATMENT, COUNT(*) FROM BILLING GROUP BY TREATMENT HAVING COUNT(*) > 2;

# Find treatments where minimum bill is below 600.
SELECT TREATMENT, MIN(TOTAL_AMOUNT) AS TOTAL_BILL FROM BILLING GROUP BY TREATMENT HAVING MIN(TOTAL_AMOUNT)<600;

# Find treatments where maximum bill exceeds 1500.
SELECT TREATMENT, MIN(TOTAL_AMOUNT) AS TOTAL_BILL FROM BILLING GROUP BY TREATMENT HAVING MIN(TOTAL_AMOUNT)>1500;

# Find patients with billing above average.
SELECT * FROM BILLING WHERE TOTAL_AMOUNT>(SELECT AVG(TOTAL_AMOUNT) FROM BILLING);

# Find patients with billing below average.
SELECT * FROM BILLING WHERE TOTAL_AMOUNT<(SELECT AVG(TOTAL_AMOUNT) FROM BILLING);

# Find bills equal to average billing.
SELECT * FROM BILLING WHERE TOTAL_AMOUNT=(SELECT AVG(TOTAL_AMOUNT) FROM BILLING);

# Find bills above maximum medicine cost.
SELECT * FROM BILLING WHERE TOTAL_AMOUNT > (SELECT MAX(MEDICINE_COST) FROM BILLING);

# Find bills where medicine cost exceeds doctor fee.
SELECT * FROM BILLING WHERE MEDICINE_COST > DOCTOR_FEE;

# Find bills where doctor fee exceeds medicine cost.
SELECT * FROM BILLING WHERE DOCTOR_FEE > MEDICINE_COST;

# Find pending payment bills.
SELECT * FROM BILLING WHERE PAYMENT_STATUS="PENDING";

# Count pending payment bills.
SELECT COUNT(*) AS PENDING_COUNT FROM BILLING WHERE PAYMENT_STATUS="PENDING";

# Count paid bills.
SELECT COUNT(*) AS PAID_COUNT FROM BILLING WHERE PAYMENT_STATUS="PAID";

# Find treatments with pending payments.
SELECT TREATMENT FROM BILLING WHERE PAYMENT_STATUS="PENDING" GROUP BY TREATMENT;

# Find treatments with paid payments.
SELECT TREATMENT FROM BILLING WHERE PAYMENT_STATUS="PAID" GROUP BY TREATMENT;

# Find average medicine cost per treatment.
SELECT TREATMENT, AVG(MEDICINE_COST) FROM BILLING GROUP BY TREATMENT;

# Find maximum medicine cost per treatment.
SELECT TREATMENT, MAX(MEDICINE_COST) FROM BILLING GROUP BY TREATMENT;

# Find minimum medicine cost per treatment.
SELECT TREATMENT, MIN(MEDICINE_COST) FROM BILLING GROUP BY TREATMENT;

# Find treatments with medicine cost above average.
SELECT * FROM BILLING WHERE MEDICINE_COST > (SELECT AVG(MEDICINE_COST) FROM BILLING);

# Find treatments with medicine cost below average.
SELECT * FROM BILLING WHERE MEDICINE_COST < (SELECT AVG(MEDICINE_COST) FROM BILLING);

# Find second highest bill.
SELECT * FROM BILLING ORDER BY TOTAL_AMOUNT DESC LIMIT 1 OFFSET 1;

# Find third highest bill.
SELECT * FROM BILLING ORDER BY TOTAL_AMOUNT DESC LIMIT 1 OFFSET 2;

# Find top 3 billing amounts.
SELECT * FROM BILLING ORDER BY TOTAL_AMOUNT DESC LIMIT 3;

# Find top 5 medicine costs.
SELECT * FROM BILLING ORDER BY MEDICINE_COST DESC LIMIT 5;

# Find billing grouped by treatment.
SELECT TREATMENT , COUNT(*) FROM BILLING GROUP BY TREATMENT;

# Find revenue per treatment.
SELECT TREATMENT , SUM(TOTAL_AMOUNT) FROM BILLING GROUP BY TREATMENT;

# Find average billing per treatment.
SELECT TREATMENT , AVG(TOTAL_AMOUNT) FROM BILLING GROUP BY TREATMENT;

# Find total doctor fee collected per treatment.
SELECT TREATMENT , SUM(DOCTOR_FEE) FROM BILLING GROUP BY TREATMENT;

# Find total medicine cost per treatment.
SELECT TREATMENT , SUM(MEDICINE_COST) FROM BILLING GROUP BY TREATMENT;

# Find treatments with highest doctor fee total.
SELECT TREATMENT , SUM(DOCTOR_FEE) FROM BILLING GROUP BY TREATMENT ORDER BY SUM(DOCTOR_FEE) DESC;

# Find treatments with highest medicine cost total.
SELECT TREATMENT , SUM(MEDICINE_COST) FROM BILLING GROUP BY TREATMENT ORDER BY SUM(MEDICINE_COST) DESC;

# Find billing percentage contribution per treatment.
SELECT TREATMENT, SUM(TOTAL_AMOUNT) * 100/(SELECT SUM(TOTAL_AMOUNT) FROM BILLING) AS PERSENTAGE FROM BILLING GROUP BY TREATMENT;

# Calculate running revenue total.
SELECT BILL_ID, TOTAL_AMOUNT, SUM(TOTAL_AMOUNT) OVER (ORDER BY BILL_ID) AS RUNNING_TOTAL FROM BILLING;

# Calculate cumulative billing.
SELECT BILL_ID, TOTAL_AMOUNT, SUM(TOTAL_AMOUNT) OVER (ORDER BY BILL_ID) AS CUMULATIVE_BILLING FROM BILLING;

# Rank treatments based on revenue.
SELECT TREATMENT, SUM(TOTAL_AMOUNT), RANK() OVER(ORDER BY SUM(TOTAL_AMOUNT) DESC) AS RANKS FROM BILLING GROUP BY TREATMENT;

# Rank treatments based on billing count.
SELECT TREATMENT, COUNT(*), RANK() OVER(ORDER BY COUNT(*) DESC) AS RANKS FROM BILLING GROUP BY TREATMENT;

# Rank bills based on amount.
SELECT BILL_ID,TOTAL_AMOUNT, RANK() OVER(ORDER BY TOTAL_AMOUNT DESC) AS RANKS FROM BILLING;

# Rank bills based on medicine cost.
SELECT BILL_ID, MEDICINE_COST, RANK() OVER(ORDER BY MEDICINE_COST DESC) AS RANKS FROM BILLING;

# Rank bills based on doctor fee.
SELECT BILL_ID, DOCTOR_FEE, RANK() OVER(ORDER BY DOCTOR_FEE DESC) AS RANKS FROM BILLING;

# Find treatments with more than one patient.
SELECT TREATMENT, COUNT(PATIENT_ID) FROM BILLING GROUP BY TREATMENT HAVING COUNT(PATIENT_ID)>1;

# Find patients with multiple billing records.
SELECT PATIENT_ID, COUNT(*) FROM BILLING GROUP BY PATIENT_ID HAVING COUNT(*)>1;

# Find treatments used by more than 2 patients.
SELECT TREATMENT, COUNT(PATIENT_ID) FROM BILLING GROUP BY TREATMENT HAVING COUNT(PATIENT_ID) > 2;

# Find treatments used by exactly one patient.
SELECT TREATMENT, COUNT(PATIENT_ID) FROM BILLING GROUP BY TREATMENT HAVING COUNT(PATIENT_ID) = 1;

# Find treatments used by exactly two patients.
SELECT TREATMENT, COUNT(PATIENT_ID) FROM BILLING GROUP BY TREATMENT HAVING COUNT(PATIENT_ID) = 2;

# Find bills where total equals doctor fee + medicine cost.
SELECT * FROM BILLING WHERE TOTAL_AMOUNT = DOCTOR_FEE + MEDICINE_COST;

# Find incorrect billing totals.
SELECT * FROM BILLING WHERE TOTAL_AMOUNT != DOCTOR_FEE + MEDICINE_COST;

# Find patients whose billing equals maximum billing.
SELECT * FROM BILLING WHERE TOTAL_AMOUNT = (SELECT MAX(TOTAL_AMOUNT) FROM BILLING);

# Find patients whose billing equals minimum billing.
SELECT * FROM BILLING WHERE TOTAL_AMOUNT = (SELECT MIN(TOTAL_AMOUNT) FROM BILLING);

# Find billing above treatment average.
SELECT * FROM BILLING B WHERE TOTAL_AMOUNT > (SELECT AVG(TOTAL_AMOUNT) FROM BILLING WHERE TREATMENT = B.TREATMENT);

# Find billing below treatment average
SELECT * FROM BILLING B WHERE TOTAL_AMOUNT < (SELECT AVG(TOTAL_AMOUNT) FROM BILLING WHERE TREATMENT = B.TREATMENT);

# Find highest bill per treatment.
SELECT TREATMENT, MAX(TOTAL_AMOUNT) FROM BILLING GROUP BY TREATMENT;

# Find lowest bill per treatment.
SELECT TREATMENT, MIN(TOTAL_AMOUNT) FROM BILLING GROUP BY TREATMENT;

# Find second highest bill per treatment.
SELECT * FROM (SELECT TREATMENT,TOTAL_AMOUNT, DENSE_RANK() OVER(PARTITION BY TREATMENT ORDER BY TOTAL_AMOUNT DESC) R FROM BILLING) x WHERE R = 2;

# Find running total per treatment.
SELECT TREATMENT, TOTAL_AMOUNT, SUM(TOTAL_AMOUNT) OVER(PARTITION BY TREATMENT ORDER BY BILL_ID) FROM BILLING;

# Find revenue difference from average.
SELECT BILL_ID, TOTAL_AMOUNT, TOTAL_AMOUNT-(SELECT AVG(TOTAL_AMOUNT) FROM BILLING) AS DIFF_FROM_AVG FROM BILLING;

# Find percentage share per bill.
SELECT BILL_ID,TOTAL_AMOUNT, (TOTAL_AMOUNT*100)/(SELECT SUM(TOTAL_AMOUNT) FROM BILLING) AS PERSENTAGE_SHARE FROM BILLING;

# Find cumulative medicine cost.
SELECT BILL_ID, MEDICINE_COST, SUM(MEDICINE_COST) OVER(ORDER BY BILL_ID) AS CUMULATIVE_MEDICINE_COST FROM BILLING;

# Find cumulative doctor fee.
SELECT BILL_ID, DOCTOR_FEE, SUM(DOCTOR_FEE) OVER(ORDER BY BILL_ID) AS CUMULATIVE_DOCTOR_FEE FROM BILLING;
