
USE HOSPITAL_DB;
## SECTION 3 — JOIN QUERIES 
# Show patient name with billing amount.
SELECT P.NAME, B.TOTAL_AMOUNT FROM PATIENTS P JOIN BILLING B ON P.PATIENT_ID = B.PATIENT_ID;

# Show patient name with treatment.
SELECT P.NAME, B.TREATMENT FROM PATIENTS P JOIN BILLING B ON P.PATIENT_ID = B.PATIENT_ID;

# Show patient name with doctor fee.
SELECT P.NAME, B.DOCTOR_FEE FROM PATIENTS P JOIN BILLING B ON P.PATIENT_ID = B.PATIENT_ID;

# Show patient name with medicine cost.
SELECT P.NAME, B.MEDICINE_COST FROM PATIENTS P JOIN BILLING B ON P.PATIENT_ID = B.PATIENT_ID;

# Show patient name with payment status.
SELECT P.NAME, B.PAYMENT_STATUS FROM PATIENTS P JOIN BILLING B ON P.PATIENT_ID = B.PATIENT_ID;

# Show patient name, disease, and treatment.
SELECT P.NAME, P.DISEASE, B.TREATMENT FROM PATIENTS P JOIN BILLING B ON P.PATIENT_ID = B.PATIENT_ID;

# Show patient name, age, and billing amount.
SELECT P.NAME, P.AGE, B.TOTAL_AMOUNT FROM PATIENTS P JOIN BILLING B ON P.PATIENT_ID = B.PATIENT_ID;

# Show patient name with admission date and bill.
SELECT P.NAME, P.ADMISSION_DATE, B.TOTAL_AMOUNT FROM PATIENTS P JOIN BILLING B ON P.PATIENT_ID = B.PATIENT_ID;

# Show patients with pending payments.
SELECT P.NAME, B.TOTAL_AMOUNT, B.PAYMENT_STATUS FROM PATIENTS P JOIN BILLING B ON P.PATIENT_ID = B.PATIENT_ID WHERE B.PAYMENT_STATUS = "PENDING";

# Show patients with paid bills.
SELECT P.NAME, B.TOTAL_AMOUNT, B.PAYMENT_STATUS FROM PATIENTS P JOIN BILLING B ON P.PATIENT_ID = B.PATIENT_ID WHERE B.PAYMENT_STATUS = "PAID";

# Find patients whose bill exceeds 1000.
SELECT P.NAME, B.TOTAL_AMOUNT FROM PATIENTS P JOIN BILLING B ON P.PATIENT_ID = B.PATIENT_ID WHERE B.TOTAL_AMOUNT > 1000;

# Find patients whose bill is below 800.
SELECT P.NAME, B.TOTAL_AMOUNT FROM PATIENTS P JOIN BILLING B ON P.PATIENT_ID = B.PATIENT_ID WHERE B.TOTAL_AMOUNT < 800;

# Find patients with highest billing.
SELECT P.NAME, B.TOTAL_AMOUNT FROM PATIENTS P JOIN BILLING B ON P.PATIENT_ID = B.PATIENT_ID WHERE B.TOTAL_AMOUNT =(SELECT MAX(TOTAL_AMOUNT) FROM BILLING);

# Find patients with lowest billing.
SELECT P.NAME, B.TOTAL_AMOUNT FROM PATIENTS P JOIN BILLING B ON P.PATIENT_ID = B.PATIENT_ID WHERE B.TOTAL_AMOUNT =(SELECT MIN(TOTAL_AMOUNT) FROM BILLING);

# Find patients with billing above hospital average.
SELECT P.NAME, B.TOTAL_AMOUNT FROM PATIENTS P JOIN BILLING B ON P.PATIENT_ID = B.PATIENT_ID WHERE B.TOTAL_AMOUNT > (SELECT AVG(TOTAL_AMOUNT) FROM BILLING);

# Find diseases generating highest revenue.
SELECT P.DISEASE, SUM(B.TOTAL_AMOUNT) AS REVENUE FROM PATIENTS P JOIN BILLING B ON P.PATIENT_ID = B.PATIENT_ID GROUP BY P.DISEASE ORDER BY REVENUE DESC LIMIT 1;

# Find diseases generating lowest revenue.
SELECT P.DISEASE, SUM(B.TOTAL_AMOUNT) AS REVENUE FROM PATIENTS P JOIN BILLING B ON P.PATIENT_ID = B.PATIENT_ID GROUP BY P.DISEASE ORDER BY REVENUE ASC LIMIT 1;

# Find revenue per disease.
SELECT P.DISEASE, SUM(B.TOTAL_AMOUNT) AS REVENUE FROM PATIENTS P JOIN BILLING B ON P.PATIENT_ID = B.PATIENT_ID GROUP BY P.DISEASE;

# Find average billing per disease.
SELECT P.DISEASE, AVG(B.TOTAL_AMOUNT) AS AVG_REVENUE FROM PATIENTS P JOIN BILLING B ON P.PATIENT_ID = B.PATIENT_ID GROUP BY P.DISEASE;

# Find maximum billing per disease.
SELECT P.DISEASE, MAX(B.TOTAL_AMOUNT) AS MAX_REVENUE FROM PATIENTS P JOIN BILLING B ON P.PATIENT_ID = B.PATIENT_ID GROUP BY P.DISEASE;

# Find minimum billing per disease.
SELECT P.DISEASE, MIN(B.TOTAL_AMOUNT) AS MIN_REVENUE FROM PATIENTS P JOIN BILLING B ON P.PATIENT_ID = B.PATIENT_ID GROUP BY P.DISEASE;

# Find diseases with most treatments.
SELECT P.DISEASE, COUNT(B.TREATMENT) AS TREAMENT_COUNT FROM PATIENTS P JOIN BILLING B ON P.PATIENT_ID = B.PATIENT_ID GROUP BY P.DISEASE ORDER BY TREAMENT_COUNT DESC LIMIT 1;

# Find diseases with least treatments.
SELECT P.DISEASE, COUNT(B.TREATMENT) AS TREAMENT_COUNT FROM PATIENTS P JOIN BILLING B ON P.PATIENT_ID = B.PATIENT_ID GROUP BY P.DISEASE ORDER BY TREAMENT_COUNT ASC LIMIT 1;

# Find patients treated for heart issues.
SELECT P.NAME,P.DISEASE, B.TREATMENT FROM PATIENTS P JOIN BILLING B ON P.PATIENT_ID=B.PATIENT_ID WHERE P.DISEASE LIKE "%HEART%";

# Find patients treated for fever.
SELECT P.NAME,P.DISEASE, B.TREATMENT FROM PATIENTS P JOIN BILLING B ON P.PATIENT_ID=B.PATIENT_ID WHERE P.DISEASE LIKE "%FEVER%";

# Find female patients with pending bills.
SELECT P.NAME, P.GENDER, B.PAYMENT_STATUS FROM PATIENTS P JOIN BILLING B ON P.PATIENT_ID=B.PATIENT_ID WHERE P.GENDER='FEMALE' AND B.PAYMENT_STATUS = "PENDING";

# Find male patients with paid bills.
SELECT P.NAME, P.GENDER, B.PAYMENT_STATUS FROM PATIENTS P JOIN BILLING B ON P.PATIENT_ID=B.PATIENT_ID WHERE P.GENDER='MALE' AND B.PAYMENT_STATUS = "PAID";

# Find total billing per patient name.
SELECT P.NAME, SUM(B.TOTAL_AMOUNT) FROM PATIENTS P JOIN BILLING B ON P.PATIENT_ID=B.PATIENT_ID GROUP BY P.NAME;

# Find patient with maximum medicine cost.
SELECT P.NAME, B.MEDICINE_COST FROM PATIENTS P JOIN BILLING B ON P.PATIENT_ID=B.PATIENT_ID WHERE MEDICINE_COST= (SELECT MAX(MEDICINE_COST) FROM BILLING);

# Find patient with maximum doctor fee.
SELECT P.NAME, B.DOCTOR_FEE FROM PATIENTS P JOIN BILLING B ON P.PATIENT_ID=B.PATIENT_ID WHERE DOCTOR_FEE= (SELECT MAX(DOCTOR_FEE) FROM BILLING);

# Find patient spending most money.
SELECT P.NAME, SUM(B.TOTAL_AMOUNT) AS TOTAL FROM PATIENTS P JOIN BILLING B ON P.PATIENT_ID=B.PATIENT_ID GROUP BY P.NAME ORDER BY TOTAL DESC LIMIT 1;

# Find patient spending least money.
SELECT P.NAME, SUM(B.TOTAL_AMOUNT) AS TOTAL FROM PATIENTS P JOIN BILLING B ON P.PATIENT_ID=B.PATIENT_ID GROUP BY P.NAME ORDER BY TOTAL ASC LIMIT 1;

# Find patients with multiple treatments.
SELECT P.NAME, COUNT(B.TREATMENT) FROM PATIENTS P JOIN BILLING B ON P.PATIENT_ID=B.PATIENT_ID GROUP BY P.NAME HAVING COUNT(B.TREATMENT) >1;

# Find treatments used by multiple diseases.
SELECT B.TREATMENT, COUNT(DISTINCT P.DISEASE) AS MUL_DISEASE FROM PATIENTS P JOIN BILLING B ON P.PATIENT_ID=B.PATIENT_ID GROUP BY B.TREATMENT HAVING COUNT(DISTINCT P.DISEASE)>1;

# Find treatments used by single disease.
SELECT B.TREATMENT, COUNT(DISTINCT P.DISEASE) AS MUL_DISEASE FROM PATIENTS P JOIN BILLING B ON P.PATIENT_ID=B.PATIENT_ID GROUP BY B.TREATMENT HAVING COUNT(DISTINCT P.DISEASE)=1;

# Find patients admitted in January with bills above 1000.
SELECT P.NAME, P.ADMISSION_DATE, B.TOTAL_AMOUNT FROM PATIENTS P JOIN BILLING B ON P.PATIENT_ID=B.PATIENT_ID WHERE MONTH(P.ADMISSION_DATE) =1 AND B.TOTAL_AMOUNT>1000;

# Find patients admitted in February with bills below 800.
SELECT P.NAME, P.ADMISSION_DATE, B.TOTAL_AMOUNT FROM PATIENTS P JOIN BILLING B ON P.PATIENT_ID=B.PATIENT_ID WHERE MONTH(P.ADMISSION_DATE) =2 AND B.TOTAL_AMOUNT<800;

# Find patients whose disease matches treatment keyword.
SELECT P.NAME,P.DISEASE,B.TREATMENT FROM PATIENTS P JOIN BILLING B ON P.PATIENT_ID=B.PATIENT_ID WHERE P.DISEASE LIKE CONCAT('%',B.TREATMENT,'%');

# Find patients whose disease differs from treatment keyword.
SELECT P.NAME,P.DISEASE,B.TREATMENT FROM PATIENTS P JOIN BILLING B ON P.PATIENT_ID=B.PATIENT_ID WHERE P.DISEASE NOT LIKE CONCAT('%',B.TREATMENT,'%');

# Find patient generating highest revenue.
SELECT P.NAME, SUM(B.TOTAL_AMOUNT) AS REVENUE FROM PATIENTS P JOIN BILLING B ON P.PATIENT_ID=B.PATIENT_ID GROUP BY P.NAME ORDER BY REVENUE DESC LIMIT 1;

# Rank patients by billing.
SELECT P.NAME, B.TOTAL_AMOUNT, RANK() OVER(ORDER BY B.TOTAL_AMOUNT DESC) AS RANKS FROM PATIENTS P JOIN BILLING B ON P.PATIENT_ID=B.PATIENT_ID;

# Rank patients by medicine cost.
SELECT P.NAME, B.MEDICINE_COST, RANK() OVER(ORDER BY B.MEDICINE_COST DESC) AS RANKS FROM PATIENTS P JOIN BILLING B ON P.PATIENT_ID=B.PATIENT_ID;

# Rank patients by doctor fee.
SELECT P.NAME, B.DOCTOR_FEE, RANK() OVER(ORDER BY B.DOCTOR_FEE DESC) AS RANKS FROM PATIENTS P JOIN BILLING B ON P.PATIENT_ID=B.PATIENT_ID;

# Rank patients within each disease by billing.
SELECT P.NAME, P.DISEASE, B.TOTAL_AMOUNT, RANK() OVER(PARTITION BY P.DISEASE ORDER BY B.TOTAL_AMOUNT DESC) AS RANKS FROM PATIENTS P JOIN BILLING B ON P.PATIENT_ID=B.PATIENT_ID;

# Rank patients within each treatment by billing.
SELECT P.NAME, B.TREATMENT, B.TOTAL_AMOUNT, RANK() OVER(PARTITION BY B.TREATMENT ORDER BY B.TOTAL_AMOUNT DESC) AS RANKS FROM PATIENTS P JOIN BILLING B ON P.PATIENT_ID=B.PATIENT_ID;

# Find highest billing patient per disease.
SELECT * FROM (SELECT P.NAME, P.DISEASE, B.TOTAL_AMOUNT,ROW_NUMBER() OVER(PARTITION BY P.DISEASE ORDER BY B.TOTAL_AMOUNT DESC) R FROM PATIENTS P JOIN BILLING B ON P.PATIENT_ID=B.PATIENT_ID) X WHERE R=1;

# Find lowest billing patient per disease.
SELECT * FROM (SELECT P.NAME, P.DISEASE, B.TOTAL_AMOUNT,ROW_NUMBER() OVER(PARTITION BY P.DISEASE ORDER BY B.TOTAL_AMOUNT ASC) R FROM PATIENTS P JOIN BILLING B ON P.PATIENT_ID=B.PATIENT_ID) X WHERE R=1;

# Find second highest billing patient per disease.
SELECT * FROM (SELECT P.NAME, P.DISEASE, B.TOTAL_AMOUNT,ROW_NUMBER() OVER(PARTITION BY P.DISEASE ORDER BY B.TOTAL_AMOUNT DESC) R FROM PATIENTS P JOIN BILLING B ON P.PATIENT_ID=B.PATIENT_ID) X WHERE R=2;

# Calculate revenue share per patient.
SELECT P.NAME, SUM(B.TOTAL_AMOUNT)*100/(SELECT SUM(TOTAL_AMOUNT) FROM BILLING) AS REVENUE_SHARE FROM PATIENTS P JOIN BILLING B ON P.PATIENT_ID=B.PATIENT_ID GROUP BY P.NAME;

# Calculate revenue share per disease.
SELECT P.NAME, P.DISEASE, SUM(B.TOTAL_AMOUNT)*100/(SELECT SUM(TOTAL_AMOUNT) FROM BILLING) AS REVENUE_SHARE FROM PATIENTS P JOIN BILLING B ON P.PATIENT_ID=B.PATIENT_ID GROUP BY P.DISEASE;

# Find cumulative revenue by patient admission date.
SELECT P.ADMISSION_DATE, SUM(B.TOTAL_AMOUNT) OVER(ORDER BY P.ADMISSION_DATE) AS CUMULATIVE_REVENUE_SHARE FROM PATIENTS P JOIN BILLING B ON P.PATIENT_ID=B.PATIENT_ID;

# Find cumulative billing by disease.
SELECT P.DISEASE, SUM(B.TOTAL_AMOUNT) OVER(ORDER BY P.DISEASE) AS CUMULATIVE_BILLING FROM PATIENTS P JOIN BILLING B ON P.PATIENT_ID=B.PATIENT_ID;

# Find running total per patient.
SELECT P.NAME, B.TOTAL_AMOUNT, SUM(B.TOTAL_AMOUNT) OVER(PARTITION BY P.NAME ORDER BY B.BILL_ID) AS RUNNING_TOTAL FROM PATIENTS P JOIN BILLING B ON P.PATIENT_ID=B.PATIENT_ID;

# Find billing difference from disease average.
SELECT P.NAME, P.DISEASE, B.TOTAL_AMOUNT, B.TOTAL_AMOUNT-AVG(TOTAL_AMOUNT)OVER(PARTITION BY P.DISEASE) AS DIFFERENCE FROM PATIENTS P JOIN BILLING B ON P.PATIENT_ID=B.PATIENT_ID;

# Find billing difference from hospital average.
SELECT P.NAME, B.TOTAL_AMOUNT, B.TOTAL_AMOUNT-(SELECT AVG(TOTAL_AMOUNT) FROM BILLING) DIFFERENCE FROM PATIENTS P JOIN BILLING B ON P.PATIENT_ID=B.PATIENT_ID;

# Find treatments whose revenue exceeds disease average revenue.
SELECT b.treatment, SUM(b.total_amount) AS treatment_revenue FROM billing b JOIN patients p ON p.patient_id = b.patient_id GROUP BY b.treatment HAVING SUM(b.total_amount) > (SELECT AVG(disease_revenue)
    FROM (SELECT SUM(b2.total_amount) AS disease_revenue FROM patients p2 JOIN billing b2 ON p2.patient_id = b2.patient_id GROUP BY p2.disease) d);

# Find patients whose billing exceeds disease average billing.
SELECT b.treatment, SUM(b.total_amount) AS treatment_revenue FROM billing b JOIN patients p ON p.patient_id = b.patient_id
GROUP BY b.treatment HAVING SUM(b.total_amount) >(SELECT AVG(disease_revenue) FROM (SELECT SUM(b2.total_amount) AS disease_revenue 
FROM patients p2 JOIN billing b2 ON p2.patient_id = b2.patient_id GROUP BY p2.disease) d);

# Find diseases whose revenue exceeds hospital average revenue.
SELECT P.NAME, P.DISEASE, B.TOTAL_AMOUNT FROM PATIENTS P JOIN BILLING B ON P.PATIENT_ID = B.PATIENT_ID
WHERE B.TOTAL_AMOUNT > (SELECT AVG(B2.TOTAL_AMOUNT) FROM PATIENTS P2 JOIN BILLING B2 ON P2.PATIENT_ID = B2.PATIENT_ID WHERE P2.DISEASE = P.DISEASE);

# Find patients whose billing equals second highest bill.
SELECT P.NAME, B.TOTAL_AMOUNT FROM PATIENTS P JOIN BILLING B ON P.PATIENT_ID = B.PATIENT_ID WHERE B.TOTAL_AMOUNT = ( SELECT MAX(TOTAL_AMOUNT) FROM BILLING WHERE TOTAL_AMOUNT < (SELECT MAX(TOTAL_AMOUNT) FROM BILLING));

# Find patients whose billing equals third highest bill.
SELECT P.NAME, B.TOTAL_AMOUNT FROM PATIENTS P JOIN BILLING B ON P.PATIENT_ID = B.PATIENT_ID WHERE B.TOTAL_AMOUNT = 
( SELECT MAX(TOTAL_AMOUNT)FROM BILLING WHERE TOTAL_AMOUNT < (SELECT MAX(TOTAL_AMOUNT) FROM BILLING WHERE TOTAL_AMOUNT < (SELECT MAX(TOTAL_AMOUNT) FROM BILLING)));

# Find diseases with revenue above 2000.
SELECT P.DISEASE, SUM(B.TOTAL_AMOUNT) AS REVENUE FROM PATIENTS P JOIN BILLING B ON P.PATIENT_ID = B.PATIENT_ID GROUP BY P.DISEASE HAVING SUM(B.TOTAL_AMOUNT) > 2000;

# Find diseases with revenue below 1000.
SELECT P.DISEASE, SUM(B.TOTAL_AMOUNT) AS REVENUE FROM PATIENTS P JOIN BILLING B ON P.PATIENT_ID = B.PATIENT_ID GROUP BY P.DISEASE HAVING SUM(B.TOTAL_AMOUNT) < 1000;

# Find diseases generating more than average revenue.
SELECT P.DISEASE, SUM(B.TOTAL_AMOUNT) AS REVENUE FROM PATIENTS P JOIN BILLING B ON P.PATIENT_ID = B.PATIENT_ID GROUP BY P.DISEASE HAVING SUM(B.TOTAL_AMOUNT) > (SELECT AVG(TOTAL_AMOUNT) FROM BILLING );

# Find patients generating more than average revenue.
SELECT P.NAME, SUM(B.TOTAL_AMOUNT) AS REVENUE FROM PATIENTS P JOIN BILLING B ON P.PATIENT_ID = B.PATIENT_ID GROUP BY P.NAME HAVING SUM(B.TOTAL_AMOUNT) > (SELECT AVG(TOTAL_AMOUNT) FROM BILLING );

# Find treatments generating more than average revenue.
SELECT B.TREATMENT, SUM(B.TOTAL_AMOUNT) AS REVENUE FROM PATIENTS P JOIN BILLING B ON P.PATIENT_ID = B.PATIENT_ID GROUP BY B.TREATMENT HAVING SUM(B.TOTAL_AMOUNT) > (SELECT AVG(TOTAL_AMOUNT) FROM BILLING );

# Find cumulative treatment revenue.
SELECT P.NAME, B.TREATMENT, SUM(B.TOTAL_AMOUNT) OVER(ORDER BY B.TREATMENT) AS CUMULATIVE_REVENUE FROM PATIENTS P JOIN BILLING B ON P.PATIENT_ID=B.PATIENT_ID;

# Find running average billing per treatment.
SELECT TREATMENT, TOTAL_AMOUNT, AVG(TOTAL_AMOUNT) OVER(PARTITION BY TREATMENT ORDER BY BILL_ID) AS RUNNING_AVG FROM BILLING;

# Find patients contributing top 20% revenue.
SELECT * FROM ( SELECT P.NAME, SUM(B.TOTAL_AMOUNT) AS REVENUE, NTILE(5) OVER(ORDER BY SUM(B.TOTAL_AMOUNT) DESC) AS GRP FROM PATIENTS P JOIN BILLING B ON P.PATIENT_ID = B.PATIENT_ID GROUP BY P.NAME ) X WHERE GRP = 1;

# Find patients contributing bottom 20% revenue.
SELECT * FROM ( SELECT P.NAME, SUM(B.TOTAL_AMOUNT) AS REVENUE, NTILE(5) OVER(ORDER BY SUM(B.TOTAL_AMOUNT)) AS GRP FROM PATIENTS P JOIN BILLING B ON P.PATIENT_ID = B.PATIENT_ID GROUP BY P.NAME ) X WHERE GRP = 1;

# Rank diseases based on revenue.
SELECT P.DISEASE, SUM(B.TOTAL_AMOUNT) AS REVENUE, RANK() OVER(ORDER BY SUM(B.TOTAL_AMOUNT) DESC) AS DISEASE_RANK FROM PATIENTS P JOIN BILLING B ON P.PATIENT_ID = B.PATIENT_ID GROUP BY P.DISEASE;
