use company;

## BETWEEN

#FIND THE EMPLOYEE WHOSE SALARY IS BETWEEN 50000 AND 70000
SELECT * FROM EMPLOYEES WHERE SALARY BETWEEN 50000 AND 70000;

#FIND THE EMPLOYEES WHOSE AGE IS BETWEEN 25 AND 30 YEARS
SELECT * FROM EMPLOYEES WHERE AGE BETWEEN 25 AND 30;

#FIND THE EMPLOYEES WHOSE HIRE DATE IS BETWEEN 2018 AND 2020
SELECT * FROM EMPLOYEES WHERE YEAR(HIRE_DATE) BETWEEN 2018 AND 2020;
SELECT * FROM EMPLOYEES WHERE HIRE_DATE BETWEEN '2018-01-01' AND '2020-12-31';

#FIND THE EMPLOYEES WHOSE AGE IS BETWEEN 30 AND 40 AND DEPARTMENT IS SALES
SELECT * FROM EMPLOYEES WHERE (AGE BETWEEN 30 AND 40) AND DEPARTMENT='SALES';

#FIND THE EMPLOYEES WHOSE EXPERIENCE BETWEEN 0 AND 3 YEAR AND CITY IS BANGALURU
SELECT * FROM EMPLOYEES WHERE (EXPERIENCE BETWEEN 0 AND 3) AND CITY= 'BENGALURU';



## NOT BETWEEN 

#FIND THE EMPLOYEES WHOSE EXPERIENCE IS NOT BETWEEN 2 AND 6 YEARS
SELECT * FROM EMPLOYEES WHERE EXPERIENCE NOT BETWEEN 2 AND 6;


## IN OPERATOR

#FIND THE EMPLOYEES WHO WORK IN DELHI, MUMBAI, OR PUNE
SELECT * FROM EMPLOYEES WHERE CITY IN("DELHI","MOMBAI","PUNE");

#FIND THE EMPLOYEE WHO DEPARTMENT IN IT, HR, FINANCE
SELECT * FROM EMPLOYEES WHERE DEPARTMENT IN("IT","HR","FINANCE");

#FIND THE EMPLOYEE WHO AGE IS ONE OF (25,27,29,31)
SELECT * FROM EMPLOYEES WHERE AGE IN(25,27,29,31);

#FIND THE EMPLOYEES WHOSE CITY IS IN DELHI AND MUMBAI AND DEPARTMENT IS HR
SELECT * FROM EMPLOYEES WHERE CITY IN ("DELHI","MUMBAI") AND DEPARTMENT ='HR';


## NOT IN OPERATOR

#FIND THE EMPLOYEE WHO CITY NOT IN (BENGALURU, HYDRABAD, PUNE)
SELECT * FROM EMPLOYEES WHERE CITY NOT IN('BENGALURU', 'HYDERABAD', 'PUNE');

#FIND THE EMPLOYEE WHO DEPARTMENT NOT IN IT AND MARKETING
SELECT * FROM employees WHERE DEPARTMENT NOT IN ('IT','MARKETING');


## LIKE OPERATOR
#FIND THE EMPLOYEE WHOSE NAMES STRATS WITH 'R';
SELECT * FROM EMPLOYEES WHERE NAME LIKE 'R%';

#FIND THE EMPLOYEE WHOSE NAMES STRATS WITH 'A';
SELECT * FROM EMPLOYEES WHERE NAME LIKE 'A%';

#FIND THE EMPLOYEE WHOSE NAMES ENDS WITH 'A';
SELECT * FROM EMPLOYEES WHERE NAME LIKE '%A';

#FIND THE EMPLOYEES WHOSE NAMES CONTAINS THE WORD OF 'SINGH';
SELECT * FROM EMPLOYEES WHERE NAME LIKE "%SINGH%";

#FIND THE EMPLOYEES WHOSE DESIGNATION STARTS WITH 'MAN'
SELECT * FROM EMPLOYEES WHERE DESIGNATION LIKE "MAN%";

#FIND THE EMPLOYEES WHOSE DEPARTMENT NAME CONTAINS THE LETTER 'I'
SELECT * FROM EMPLOYEES WHERE DEPARTMENT LIKE "%I%";


## NOT LIKE

#FIND THE EMPLOYEES WHOSE NAMES DO NOT STARTS WITH 'R'
SELECT * FROM EMPLOYEES WHERE NAME NOT LIKE 'R%';

#FIND THE EMPLOYEES WHO DEPARTMENT DOES NOT CONTAIN THE 'I'
SELECT * FROM EMPLOYEES WHERE DEPARTMENT NOT LIKE '%I%';