CREATE DATABASE COM_RB;

USE COM_RB;

CREATE TABLE STUDENTS(
ROLL_NO INT PRIMARY KEY,
MARKS INT
);

INSERT INTO STUDENTS VALUES (1,100),(2,200);
COMMIT;    ## IT STORE THE DATA INTO THE DATABASE PERMENTENT WE CAN'T UNDO IT

INSERT INTO STUDENTS VALUES (3,300),(4,400);

SELECT * FROM STUDENTS;

INSERT INTO STUDENTS VALUES (5,500),(6,600);

UPDATE STUDENTS SET MARKS = 1000 WHERE ROLL_NO = 2;

ROLLBACK;    ## IF WE CAN NOT STORE IT PERMENANTLY WE CAN UNDO THE DATABASE CHANGES
			 ## IT CAN ALSO APPLICABLE ON THE OTHER OPERATIONS

