 #### SUBQUERY #####
 ## SCALAR SUBQUERY - ONE ANSWER
		#SELECT COLUMN1, COLUMN2,.. FROM TABLE_NAME WHERE COLUMN_NAME OPERATOR(SELECT COLUMN1 FROM TABLE_NAME WHERE CONDITION);
        
 ## CORRELATED SUBQUERY - IT IS A QUERY INSIDE ANOTHER QUERY THAT DEPENDS ON EACH ROW OF THE OUTER QUERY
 ## 					  THE INNER QUERY CANNOT RUN ALONE
 		#SELECT COLUMN1, COLUMN2,.. FROM TABLE_NAME WHERE COLUMN_NAME OPERATOR(SELECT COLUMN1, FROM TABLE_NAME WHERE CONDITION);

 ## NESTED SUBQUERY
		#SELECT COLUMN1, COLUMN2,.. FROM TABLE_NAME WHERE COLUMN_NAME OPERATOR(SELECT COLUMN1, FROM TABLE_NAME WHERE CONDITION);

 ## FILTER
 ## AGGRIGATION
 
 use subquery;
 
 CREATE TABLE employees1 (
    emp_id INT PRIMARY KEY,
    emp_name VARCHAR(50),
    gender VARCHAR(10),
    department VARCHAR(30),
    designation VARCHAR(30),
    salary DECIMAL(10,2),
    city VARCHAR(30),
    experience_years INT
);
 
 INSERT INTO employees1 VALUES
(1,  'Amit',   'Male',   'HR',        'Manager',       75000, 'Delhi',      8),
(2,  'Sneha',  'Female', 'HR',        'Executive',     55000, 'Delhi',      3),
(3,  'Divya',  'Female', 'HR',        'Executive',     54000, 'Delhi',      2),
(4,  'Neha',   'Female', 'Finance',   'Analyst',       62000, 'Mumbai',     4),
(5,  'Karan',  'Male',   'Finance',   'Accountant',    58000, 'Mumbai',     3),
(6,  'Rahul',  'Male',   'Finance',   'Manager',       90000, 'Mumbai',    10),
(7,  'Meena',  'Female', 'Finance',   'Analyst',       61000, 'Mumbai',     5),
(8,  'Ravi',   'Male',   'IT',        'Developer',     85000, 'Bangalore',  6),
(9,  'Vikram', 'Male',   'IT',        'Developer',     88000, 'Hyderabad',  7),
(10, 'Rajesh', 'Male',   'IT',        'Manager',       95000, 'Hyderabad', 10),
(11, 'Pooja',  'Female', 'IT',        'Developer',     83000, 'Bangalore',  5),
(12, 'Manoj',  'Male',   'IT',        'Tester',        60000, 'Pune',       3),
(13, 'Priya',  'Female', 'Marketing', 'Manager',       72000, 'Chennai',    8),
(14, 'Anjali', 'Female', 'Marketing', 'Executive',     51000, 'Kolkata',    2),
(15, 'Suresh', 'Male',   'Marketing', 'Executive',     50000, 'Kolkata',    1);


## CORRELATED SUBQUERY
#FIND THE EMPLOYEES EARNING MORE THAN THE AVERAGE SALARY OF THEIR DEPARTMENT
SELECT EMP_NAME, DEPARTMENT, SALARY FROM EMPLOYEES1 E1 WHERE SALARY>
(SELECT AVG(SALARY) FROM EMPLOYEES1 E2 WHERE E2.DEPARTMENT =E1.DEPARTMENT);

#FIND THE EMPLOYEES WITH THE HIGHEST SALARY IN THE DEPARTMENT
SELECT EMP_NAME, DEPARTMENT, SALARY FROM EMPLOYEES1 E1 WHERE SALARY =
(SELECT MAX(SALARY) FROM EMPLOYEES1 E2 WHERE E2.DEPARTMENT =E1.DEPARTMENT);

#FIND THE EMPLOYEES EARNING LESS THAN AVG SALARY OF THEIR DEPARTMENT
SELECT EMP_NAME, DEPARTMENT, SALARY FROM EMPLOYEES1 E1 WHERE SALARY<
(SELECT AVG(SALARY) FROM EMPLOYEES1 E2 WHERE E2.DEPARTMENT =E1.DEPARTMENT);

#FIND THE EMPLOYEES WITH THE MAXIMUM EXPERIENCE IN THEIR DEPARTMENT
SELECT EMP_NAME, DEPARTMENT, EXPERIENCE_YEARS FROM EMPLOYEES1 E1 WHERE EXPERIENCE_YEARS =
(SELECT MAX(EXPERIENCE_YEARS) FROM EMPLOYEES1 E2 WHERE E2.DEPARTMENT =E1.DEPARTMENT);

#FIND THE EMPLOYEES WHOSE SALARY IS GREATER THAN THE MINIMUM SALARY IN THEIR CITY
SELECT EMP_NAME, CITY, SALARY FROM EMPLOYEES1 E1 WHERE SALARY >
(SELECT MIN(SALARY) FROM EMPLOYEES1 E2 WHERE E2.CITY =E1.CITY);

#FIND THE DEPARTMENT WHERE ALL EMPLOYEES EARE MORE THAN $60,000
x SELECT EMP_NAME,DEPARTMENT,SALARY FROM EMPLOYEES1 E1 WHERE SALARY>'60,000'; 
x SELECT EMP_NAME,DEPARTMENT,SALARY FROM EMPLOYEES1 E1 WHERE DEPARTMENT=(SELECT DEPARTMENT FROM EMPLOYEES1 E2 WHERE SALARY>"60000" E2.DEPARTMENT= E1.DEPARTMENT); 

#FIND THE EMPLLOYEES WHOSE EXPERIENCE IS GREATER THAN AVG EXPERIENCE THEIR CITY
SELECT EMP_NAME, CITY, EXPERIENCE_YEARS FROM EMPLOYEES1 E1 WHERE EXPERIENCE_YEARS >
(SELECT AVG(EXPERIENCE_YEARS) FROM EMPLOYEES1 E2 WHERE E2.CITY =E1.CITY);