use company;
select * from employees;

#FIND THE EMPLOYEES WHO WORKS IN THE IT DEPT HAVE A SALARY GREATER THEN 60000 AND ARE FROM BENGALURU OR PUNE
SELECT * FROM EMPLOYEES WHERE DEPARTMENT = 'IT' AND SALARY >60000 AND CITY IN ('BENGALURU','PUNE');

#FIND THE EMPLOYEES WHOSE AGE IS BTW 25 AND 39 AND DESIGN IS CONTAINS 'DEV'
SELECT * FROM EMPLOYEES WHERE (AGE BETWEEN 25 AND 30) AND DESIGNATION LIKE "%DEV%";

#FIND THE EMPLOYEES WHO ARE FEMALE, SALARY LESS THEN 60000 AND DEPT NOT EQUL TO HR
SELECT * FROM EMPLOYEES WHERE GENDER='F' AND SALARY <60000 AND DEPARTMENT !='HR';

#FIND THE EMPLOYEES WHOSE DESING STARTS WITH 'MAN' AND EXPERIENCE IS 5 YEARS OR MORE
SELECT * FROM EMPLOYEES WHERE DESIGNATION LIKE "MAN%" AND EXPERIENCE>=5;

#FIND THE EMPLOYEES FROM DELHI OR MUMBAI , GOA , CHENNAI WHOSE SALARY IS BTW 50000 AND 90000
SELECT * FROM EMPLOYEES WHERE CITY IN('DELHI','MUMBAI','GOA','CHENNAI') AND SALARY BETWEEN 50000 AND 90000;

#FIND THE EMPLOYEES WHOSE EXPERIENCE IS BTW 5 AND 10 DESIGN CONTAINS MANAGER AND CITY IS NOT NULL 
SELECT * FROM EMPLOYEES WHERE (EXPERIENCE BETWEEN 5 AND 10) AND DESIGNATION LIKE "%MANAGER%" AND CITY IS NOT NULL;

#FIND THE EMPLOYEES WHOSE SALARY IS MISSING OR NAME STARTS WITH 'P' AND DEPRT IS IT
SELECT * FROM EMPLOYEES WHERE (SALARY IS NULL OR NAME LIKE "P%") AND DEPARTMENT ='IT';

#FIND THE EMPLOYEES WHO JOINED BTW 2018 AND 2022 AND DEPT IT AND FINANCE AND SALARY GREATER THEN 55000
SELECT * FROM EMPLOYEES WHERE (YEAR(HIRE_DATE) BETWEEN 2018 AND 2022) AND DEPARTMENT IN ('IT','FINANCE') AND SALARY >55000;

#FIND THE EMPLOYEES WHO DONT BELONG TO FINANCE AND WHOSE NAME NOSNOT CONTAIN 'A'
SELECT * FROM EMPLOYEES WHERE (DEPARTMENT !='FINANCE') AND NAME NOT LIKE ("%A%");