
CREATE DATABASE MODIFYS;

USE MODIFYS;

CREATE TABLE employees (
    emp_id INT AUTO_INCREMENT PRIMARY KEY,
    first_name VARCHAR(50),
    last_name VARCHAR(50),
    department VARCHAR(50),
    salary DECIMAL(10,2),
    hire_date DATE
);


INSERT INTO employees (first_name, last_name, department, salary, hire_date)
VALUES
('Alice', 'Johnson', 'HR', 55000.00, '2019-03-15'),
('Bob', 'Smith', 'IT', 72000.00, '2020-01-22'),
('Charlie', 'Brown', 'Finance', 68000.00, '2018-11-10'),
('Diana', 'Miller', 'IT', 75000.00, '2021-07-05'),
('Ethan', 'Williams', 'Marketing', 60000.00, '2017-09-19'),
('Fiona', 'Taylor', 'Finance', 69000.00, '2018-05-30'),
('George', 'Anderson', 'IT', 71000.00, '2019-08-12'),
('Hannah', 'Moore', 'HR', 56000.00, '2022-02-25'),
('Ian', 'Clark', 'Marketing', 61000.00, '2021-03-17'),
('Jane', 'Lee', 'Finance', 70000.00, '2020-10-08');


SELECT * FROM EMPLOYEES;

### ALTER SYNTAX


## ADD A NEW COLUMN TO THE TABLE
/*
ALTER TABLE TABLE_NAME 
ADD COLUMN_NAME DATATYPE;
*/

ALTER TABLE EMPLOYEES 
ADD EMAIL_ID VARCHAR(40);

SELECT * FROM EMPLOYEES;


## REMOVE THE COLUMN FROM THE TABLE 
/*
ALTER TABLE TABLE_NAME
DROP COLUMN_NAME
*/
ALTER TABLE employees
DROP EMAIL_ID;

SELECT * FROM EMPLOYEES;

## RENAME COLUMN
/*
ALTER TABLE TABLE_NAME
CHANGE COLUMN OLD_NAME NEW_NAME DATATYPE;
*/

ALTER TABLE EMPLOYEES 
CHANGE COLUMN DEPARTMENT DEPT_NAME VARCHAR(50);

SELECT * FROM EMPLOYEES;


# NEW TABLE
CREATE TABLE employees1 (
    emp_id INT,
    first_name VARCHAR(50),
    last_name VARCHAR(50),
    department VARCHAR(50),
    salary DECIMAL(10,2),
    hire_date DATE
);

DESCRIBE EMPLOYEES1;

## ADD CONSTRINT

# ADD PRIMARY KEY
/*
ALTER TABLE TABLE_NAME 
ADD CONSTRAINT CONSTRAINT_NAME(COLUMN_NAME);
*/

ALTER TABLE EMPLOYEES1
ADD CONSTRAINT PRIMARY KEY(EMP_ID);


# ADD NOT NULL
/*
ALTER TABLE TABLE_NAME 
MODIFY COLUMN_NAME DATATYPE CONSTRAINT_NAME;
*/

ALTER TABLE EMPLOYEES1
MODIFY FIRST_NAME VARCHAR(20) NOT NULL;

# ADD UNIQUE
/*
ALTER TABLE TABLE_NAME 
ADD CONSTRAINT CONSTRAINT_NAME(COLUMN_NAME);
*/
ALTER TABLE EMPLOYEES1
ADD CONSTRAINT UNIQUE(LAST_NAME);

DESC EMPLOYEES1;

# ADD CHECK
/*
ALTER TABLE TABLE_NAME 
ADD CONSTRAINT COLUMN_NAME CONSTRAINT_NAME(COLUMN_NAME);
*/

ALTER TABLE EMPLOYEES1
ADD CONSTRAINT CHK_SALARY CHECK(SALARY>0);

INSERT INTO EMPLOYEES1 VALUES(1,'BALA','SURIYA','IT',-10000,'12.6.2020'); # IT BECOME ERROR

SELECT * FROM EMPLOYEES1;

## DROP CONSTRAINTS
# DROP PRIMARY KEY
/*
ALTER TABLE TABLE_NAME
DROP PRIMARY KEY;
*/
ALTER TABLE EMPLOYEES1
DROP PRIMARY KEY;

#DROP UNIQUE
/*
ALTER TABLE TABLE_NAME
DROP INDEX COLUMN_NAME;
*/
ALTER TABLE EMPLOYEES1
DROP INDEX LAST_NAME;

# DROP CHECK
/*
ALTER TABLE TABLE_NAME
DROP CHECK REFERENCE_NAME;
*/
ALTER TABLE EMPLOYEES1
DROP CHECK CHK_SALARY;

# DROP NOT NULL
/*
ALTER TABLE TABLE_NAME
MODIFY COLUMN_NAME DATATYPE NULL;
*/
ALTER TABLE EMPLOYEES1
MODIFY EMP_ID INT NULL;

ALTER TABLE EMPLOYEES1
MODIFY FIRST_NAME VARCHAR(20) NULL;

DESC EMPLOYEES1;


## MODIFY DATATYPE
/*
ALTER TABLE TABLE_NAME
MODIFY COLUMN COLUMN_NAME DATATYPE;
*/

ALTER TABLE EMPLOYEES1 
MODIFY COLUMN SALARY DECIMAL(12,2);

ALTER TABLE EMPLOYEES1 
MODIFY COLUMN EMP_ID BIGINT;

ALTER TABLE EMPLOYEES1 
MODIFY COLUMN FIRST_NAME VARCHAR(50);

ALTER TABLE EMPLOYEES1 
MODIFY COLUMN HIRE_DATE DATETIME;

DESC EMPLOYEES1;

USE CLG;
## DROP COMMEND -> IT DELETE COMPLETE TABLE FROM THE DATABASE
# DROP TABLE TABLE_NAME;
DROP TABLE IIR;

## TRUNCATE -> IT DELETE COMPLETE DATA FROM THE TABLE 
# TRUNCATE TABLE_NAME;
TRUNCATE EMPLOYEES;

## DELETE -> IT DELETE THE SPECIFIC ROW FROM THE TABLE
# DELETE FROM TABLE_NAME WHERE COLUMN = VALUE; - SPECIFIC COLUMN
# DELETE FROM TABLE_NAME; - ALL COLUMN


