 #### SUBQUERY #####
 ## SCALAR SUBQUERY - ONE ANSWER
		# SELECT COLUMN1, COLUMN2,.. FROM TABLE_NAME 
        # WHERE COLUMN_NAME OPERATOR(SELECT COLUMN1 FROM TABLE_NAME WHERE CONDITION);
        
 ## CORRELATED SUBQUERY - IT IS A QUERY INSIDE ANOTHER QUERY THAT DEPENDS ON EACH ROW OF THE OUTER QUERY
 ## 					  THE INNER QUERY CANNOT RUN ALONE
 		# SELECT COLUMN1, COLUMN2,.. FROM TABLE_NAME 
        # WHERE COLUMN_NAME OPERATOR(SELECT COLUMN_NAME FROM TABLE_NAME WHERE CONDITION);

 ## NESTED SUBQUERY - A ONE SUBQUERY INSIDE ANOTHER SUBQUERY
			# There are Three Types
				#1. INNERMOST QUERY - SELECT COL_NAME FROM TAB_NAME WHERE CONDITION;
                #2. MIDDLE QUERY -  SELECT COL_NAME FROM TAB_NAME WHERE COL_NAME OPERATOR (--RESULT FROM INNERMOST QUERY--);
                #3. OUTER QUERY -  SELECT COL1, COL2 FROM TAB_NAME WHERE COL_NAME OPERATOR(--RESULT FROM MIDDLE QUERY--);
                
		# SELECT COLUMN1, COLUMN2,.. FROM TABLE_NAME 
        # WHERE COLUMN_NAME OPERATOR(SELECT COLUMN1, FROM TABLE_NAME 
        # WHERE OPERATOR(SELECT COLUMN_NAME FROM TABLE WHERE CONDITION));

 ## FILTER
 
 ## AGGRIGATION
 
USE subquery;
 
CREATE TABLE employees2 (
    emp_id INT PRIMARY KEY,
    emp_name VARCHAR(50),
    gender VARCHAR(10),
    department VARCHAR(30),
    designation VARCHAR(30),
    salary DECIMAL(10,2),
    city VARCHAR(30),
    experience_years INT
);


INSERT INTO employees2 VALUES
(1,  'Amit',   'Male',   'HR',        'Manager',       75000, 'Delhi',      8),
(2,  'Sneha',  'Female', 'HR',        'Executive',     55000, 'Delhi',      3),
(3,  'Divya',  'Female', 'HR',        'Executive',     54000, 'Delhi',      2),
(4,  'Neha',   'Female', 'Finance',   'Analyst',       62000, 'Mumbai',     4),
(5,  'Karan',  'Male',   'Finance',   'Accountant',    58000, 'Mumbai',     3),
(6,  'Rahul',  'Male',   'Finance',   'Manager',       90000, 'Mumbai',    10),
(7,  'Meena',  'Female', 'Finance',   'Analyst',       61000, 'Mumbai',     5),
(8,  'Ravi',   'Male',   'IT',        'Developer',     85000, 'Bangalore',  6),
(9,  'Vikram', 'Male',   'IT',        'Developer',     88000, 'Hyderabad',  7),
(10, 'Rajesh', 'Male',   'IT',        'Manager',       95000, 'Hyderabad', 10),
(11, 'Pooja',  'Female', 'IT',        'Developer',     83000, 'Bangalore',  5),
(12, 'Manoj',  'Male',   'IT',        'Tester',        60000, 'Pune',       3),
(13, 'Priya',  'Female', 'Marketing', 'Manager',       72000, 'Chennai',    8),
(14, 'Anjali', 'Female', 'Marketing', 'Executive',     51000, 'Kolkata',    2),
(15, 'Suresh', 'Male',   'Marketing', 'Executive',     50000, 'Kolkata',    1);


SELECT * FROM EMPLOYEES2;

## NESTED SUBQUERY

#FIND THE EMPLOYEES WHO EARN THE SAME SALARY AS THE HIGHEST PAID AS HR EMPLOYEE
# innermost query
SELECT MAX(SALARY) FROM EMPLOYEES2 WHERE DEPARTMENT = 'HR';

# middle query
SELECT SALARY FROM EMPLOYEES2 WHERE SALARY = ( SELECT MAX(SALARY) FROM EMPLOYEES2 WHERE DEPARTMENT = 'HR');

# outer query
SELECT EMP_NAME, DEPARTMENT, SALARY FROM EMPLOYEES2
	WHERE SALARY = ( SELECT SALARY FROM EMPLOYEES2 
		WHERE SALARY = ( SELECT MAX(SALARY) FROM EMPLOYEES2 WHERE DEPARTMENT = 'HR'));


# FIND THE EMPLOYEE IWHO WORK IN THE SAME CITY AS THE HIGHEST PAID EMPLOYEE
# innermost query
SELECT MAX(SALARY) FROM EMPLOYEES2;

# middle query
SELECT CITY FROM EMPLOYEES2 WHERE SALARY = (SELECT MAX(SALARY) FROM EMPLOYEES2);

# outer query
SELECT EMP_NAME, DEPARTMENT, CITY, SALARY FROM EMPLOYEES2 
	WHERE CITY=(SELECT CITY FROM EMPLOYEES2 
		WHERE SALARY = (SELECT MAX(SALARY) FROM EMPLOYEES2));


# FIND THE EMPLOYEES WHO WORKS IN THE SAME DEPARTMENT AS THOSE LOCATED IN MUMBAI
SELECT DEPARTMENT FROM EMPLOYEES2 WHERE CITY="MUMBAI";

SELECT EMP_NAME, DEPARTMENT, CITY FROM EMPLOYEES2
WHERE DEPARTMENT IN(SELECT DEPARTMENT FROM EMPLOYEES2 WHERE CITY="MUMBAI");


## ANY - 
# EMPLOYEES WHOSE SALARY GREATER THAN ANY HR EMPLOYEES
SELECT SALARY FROM EMPLOYEES2 WHERE DEPARTMENT= "HR";

SELECT EMP_NAME, DEPARTMENT, SALARY FROM EMPLOYEES2 
	WHERE SALARY > ANY(SELECT SALARY FROM EMPLOYEES2 WHERE DEPARTMENT= "HR");

## ALL
#EMPLOYEES WHOSE SALARY IS GREATER THAN ALL HR EMPLOYEES
SELECT SALARY FROM EMPLOYEES2 WHERE DEPARTMENT= "HR";

SELECT EMP_NAME, DEPARTMENT, SALARY FROM EMPLOYEES2 
	WHERE SALARY > ALL(SELECT SALARY FROM EMPLOYEES2 WHERE DEPARTMENT= "HR");
    
#EMPLOYEES WHO EARN LESS THAN ALL IT EMPLOYEES
SELECT SALARY FROM EMPLOYEES2 WHERE DEPARTMENT= "IT";

SELECT EMP_NAME, DEPARTMENT, SALARY FROM EMPLOYEES2 
	WHERE SALARY < ALL(SELECT SALARY FROM EMPLOYEES2 WHERE DEPARTMENT= "IT");
    
#FIND THE EMPLOYEE WHOSE SALARY IS EQUAL TO ANY AVG SALARY OF EACH DEPARTMENT 
SELECT DEPARTMENT, AVG(SALARY) AS AVG_SALARY FROM EMPLOYEES2 GROUP BY DEPARTMENT;

SELECT EMP_NAME, DEPARTMENT, SALARY FROM EMPLOYEES2 
	WHERE SALARY = ANY(SELECT ROUND(AVG(SALARY)) AS AVG_SALARY 
		FROM EMPLOYEES2 GROUP BY DEPARTMENT);