 #### SUBQUERY #####
 ## SCALAR SUBQUERY - ONE ANSWER
		#SELECT COLUMN1, COLUMN2,.. FROM TABLE_NAME WHERE COLUMN_NAME OPERATOR(SELECT COLUMN1 FROM TABLE_NAME WHERE CONDITION);
        
 ## CORRELATED SUBQUERY - IT IS A QUERY INSIDE ANOTHER QUERY THAT DEPENDS ON EACH ROW OF THE OUTER QUERY
 ## 					  THE INNER QUERY CANNOT RUN ALONE
 		#SELECT COLUMN1, COLUMN2,.. FROM TABLE_NAME WHERE COLUMN_NAME OPERATOR(SELECT COLUMN1, FROM TABLE_NAME WHERE CONDITION);

 ## NESTED SUBQUERY
		#SELECT COLUMN1, COLUMN2,.. FROM TABLE_NAME WHERE COLUMN_NAME OPERATOR(SELECT COLUMN1, FROM TABLE_NAME WHERE CONDITION);

 ## FILTER
 ## AGGRIGATION
 
 CREATE DATABASE subquery;
 
 USE subquery;
 
 CREATE TABLE employees (
    emp_id INT PRIMARY KEY,
    emp_name VARCHAR(50),
    gender VARCHAR(10),
    department VARCHAR(30),
    designation VARCHAR(30),
    salary DECIMAL(10,2),
    city VARCHAR(30)
);


INSERT INTO employees (emp_id, emp_name, gender, department, designation, salary, city) VALUES
(1,  'Amit',     'Male',   'HR',        'Manager',       75000, 'Delhi'),
(2,  'Neha',     'Female', 'Finance',   'Analyst',       62000, 'Mumbai'),
(3,  'Ravi',     'Male',   'IT',        'Developer',     85000, 'Bangalore'),
(4,  'Sneha',    'Female', 'HR',        'Executive',     55000, 'Delhi'),
(5,  'Vikram',   'Male',   'IT',        'Developer',     88000, 'Hyderabad'),
(6,  'Priya',    'Female', 'Marketing', 'Manager',       72000, 'Chennai'),
(7,  'Karan',    'Male',   'Finance',   'Accountant',    58000, 'Mumbai'),
(8,  'Anjali',   'Female', 'Marketing', 'Executive',     51000, 'Kolkata'),
(9,  'Manoj',    'Male',   'IT',        'Tester',        60000, 'Pune'),
(10, 'Divya',    'Female', 'HR',        'Executive',     54000, 'Delhi'),
(11, 'Rahul',    'Male',   'Finance',   'Manager',       90000, 'Mumbai'),
(12, 'Pooja',    'Female', 'IT',        'Developer',     83000, 'Bangalore'),
(13, 'Suresh',   'Male',   'Marketing', 'Executive',     50000, 'Kolkata'),
(14, 'Meena',    'Female', 'Finance',   'Analyst',       61000, 'Mumbai'),
(15, 'Rajesh',   'Male',   'IT',        'Manager',       95000, 'Hyderabad');

SELECT * FROM EMPLOYEES;

## SCALAR -> ONE ANSWER
#EMPLOYEES EARNING ABOVE AVERAGE OF THE SALARY
#STEP-1 INNER QUERY
SELECT AVG(SALARY) FROM EMPLOYEES;
#STEP-2 OUTER QUERY
SELECT EMP_NAME, DEPARTMENT, SALARY FROM EMPLOYEES WHERE SALARY > (SELECT AVG(SALARY) FROM EMPLOYEES);

#EMPLOYEES EARNING EQUAL TO MINIMUM SALARY
SELECT EMP_NAME, DEPARTMENT, SALARY FROM EMPLOYEES WHERE SALARY = (SELECT MIN(SALARY) FROM EMPLOYEES);

#FIND THEE EMPLOYEE WITH THE SAME SALARY AS THE HIGHEST PAID FINANCE EMPLOYEE
SELECT EMP_NAME, DEPARTMENT, SALARY FROM EMPLOYEES 
WHERE SALARY = (SELECT MAX(SALARY) FROM EMPLOYEES WHERE DEPARTMENT="FINANCE");

#WHO IS GET THE HIGHEST SALARY IN THE IT DEPARTMENT
SELECT EMP_NAME, DEPARTMENT, SALARY FROM EMPLOYEES 
WHERE DEPARTMENT="IT" AND SALARY = (SELECT MAX(SALARY) FROM EMPLOYEES);

#FIND THE DEPARTMENT OF HIGHEST PAID EMPLOYEE
SELECT EMP_NAME, DEPARTMENT, SALARY FROM EMPLOYEES 
WHERE SALARY = (SELECT MAX(SALARY) FROM EMPLOYEES);

#FIND THE EMPLOYEE WHO GETING LOWEST SALARY IN FEMALE
SELECT EMP_NAME, DEPARTMENT, SALARY FROM EMPLOYEES WHERE SALARY = (SELECT MIN(SALARY) FROM EMPLOYEES WHERE GENDER = "FEMALE");

#SHOW EMPLOYEES WHOSE SALARY IS GREATER THAN THE AVERAGE SALARY OF HR DEPARTMENT
SELECT EMP_NAME, DEPARTMENT, SALARY FROM EMPLOYEES WHERE SALARY>(SELECT AVG(SALARY) FROM EMPLOYEES WHERE DEPARTMENT="HR");

#FIND THE EMPLOYEES WORKING IN THE SAME CITY OF HIGHEST PAID EMPLOYEE
SELECT EMP_NAME, DEPARTMENT, CITY, SALARY FROM EMPLOYEES 
WHERE CITY = (SELECT CITY FROM EMPLOYEES WHERE SALARY=(SELECT MAX(SALARY) FROM EMPLOYEES));

#SHOW THE EMPLOYEE WHOSE SALARY IS GREATER THEN THE PRIYA'S SALARY
SELECT EMP_NAME, DEPARTMENT, SALARY FROM EMPLOYEES WHERE SALARY>(SELECT SALARY FROM EMPLOYEES WHERE EMP_NAME="PRIYA");

#SHOW EMPLOYEES FROM THE SAME DEPARTMENT AS AMIT
SELECT * FROM EMPLOYEES WHERE DEPARTMENT =(SELECT DEPARTMENT FROM EMPLOYEES WHERE EMP_NAME="AMIT");

#FIND THEE EMPLOYEES WHO EARNN MORE THAN THE LOWEST PAID MANAGER
SELECT * FROM EMPLOYEES WHERE SALARY> (SELECT MIN(SALARY) FROM EMPLOYEES WHERE DESIGNATION = "MANAGER");

