USE JOINS_DB;

CREATE TABLE employees (
    emp_id INT PRIMARY KEY,
    emp_name VARCHAR(100),
    department VARCHAR(50),
    manager_id INT
);

INSERT INTO employees (emp_id, emp_name, department, manager_id)
VALUES
(1, 'Anil Sharma', 'HR', NULL),
(2, 'Priya Verma', 'HR', 1),
(3, 'Rahul Mehta', 'Sales', 1),
(4, 'Sunita Das', 'Sales', 3),
(5, 'Karan Patel', 'IT', 3),
(6, 'Neha Gupta', 'IT', 5),
(7, 'Arjun Rao', 'HR', 2);


select * FROM EMPLOYEES;

## SELF JOIN
#SHOW EACH EMPLOYEE NAME ALONG WITH MANAGERS NAME
SELECT 
	E.EMP_NAME AS EMPLOYEES,
    M.EMP_NAME AS MANAGER 
FROM 
	EMPLOYEES E LEFT JOIN EMPLOYEES M
ON 
	E.MANAGER_ID=M.EMP_ID;
    
# LIST ALL EMPLOYEE AND THEIR DEPARTMENT AND MANAGER AND THEIR DEPARTMENTS
SELECT 
	E.EMP_NAME AS EMPLOYEES,
    E.DEPARTMENT AS EMPLOYEE_DEPT,
    M.EMP_NAME AS MANAGER,
    M.DEPARTMENT AS NAMAGER_DEPT
FROM 
	EMPLOYEES E LEFT JOIN EMPLOYEES M
ON 
	E.MANAGER_ID=M.EMP_ID;
    
# FIND EMPLOYEES WHO ARE MANAGERS
SELECT DISTINCT
	M.EMP_NAME AS MANAGER
FROM
	EMPLOYEES E JOIN EMPLOYEES M 
ON 
	E.MANAGER_ID = M.EMP_ID;
    
# COUNT HOW MANY EMPLOYEES EACH MANAGER HAS
SELECT 
	M.EMP_NAME AS MANAGER,
    COUNT(E.EMP_ID) AS NO_OF_EMPLOYEES
FROM 
	EMPLOYEES E INNER JOIN EMPLOYEES M
ON 
	E.MANAGER_ID = M.EMP_ID
GROUP BY M.EMP_NAME;