create database join_db2;

use join_db2;

CREATE TABLE employees (
    emp_id INT PRIMARY KEY,
    emp_name VARCHAR(50),
    manager_id INT
);

INSERT INTO employees (emp_id, emp_name, manager_id)
VALUES
(1, 'Raj', NULL),
(2, 'Sita', 1),
(3, 'Mohan', 1),
(4, 'Rani', 2),
(5, 'Amit', 3);

## SELF JOIN
#WE WANT TO SHOW EACH EMPLOYEE WITH THEIR 
SELECT 
	E.EMP_NAME AS EMPLOYEE,
    M.EMP_NAME AS MANAGER 
FROM 
	EMPLOYEES E LEFT JOIN EMPLOYEES M 
ON 
	E.MANAGER_ID = M.EMP_ID;
    
#FIND THE EMPLOYEE WHO DOESN'T HAVE MANAGER
SELECT EMP_NAME AS EMPLOYEE FROM EMPLOYEES WHERE MANAGER_ID IS NULL;
    
#COUNT HOW MANY EMPLOYEES EACH MANAGER HAS
SELECT 
	M.EMP_NAME AS MANAGER,
    COUNT(E.EMP_ID) AS TEAM_SIZE
FROM EMPLOYEES E JOIN EMPLOYEES M 
ON E.MANAGER_ID = M.EMP_ID 
GROUP BY M.EMP_NAME;

#