### TRIGGER
	# TRIGGER IS A DATABASE OBJECT THAT AUTOMATICALY RUNS WHEN AN EVENT OCCURS ON A TABLES
    
# USE OF TRIGER
	# AUTOMATIC DATA VALIDATION
    # AUDIT / LOG TRACKING
    
/*

CREATE TRIGGER <TRIGGER_NAME>
{BEFORE|AFTER}{INSERT|UPDATE|DELETE}
ON <TABLE_NAME>
FOR EACH ROW
BEGIN 
	-- SQL statement (trigger body)
END;

*/

CREATE DATABASE triger;

USE triger;

CREATE TABLE customers(
CUST_ID INT,
AGE INT,
NAME VARCHAR(30)
);


## BEFORE INSERT

DELIMITER //

CREATE TRIGGER AGE_VERIFY
BEFORE INSERT
ON CUSTOMERS
FOR EACH ROW
IF NEW.AGE < 14 THEN SET NEW.AGE = 0;

END IF //

INSERT INTO CUSTOMERS VALUES (101, 18, "VIRAT"),(102, 10, "KHOLI"),(103, 15, "RAVI");//

SELECT * FROM CUSTOMERS;//

TRUNCATE CUSTOMERS;//


## AFTER INSERT

CREATE TABLE CUSTOMERS1(
ID INT AUTO_INCREMENT PRIMARY KEY,
NAME VARCHAR(40) NOT NULL,
EMAIL VARCHAR(50),
BIRTH_DATE DATE);//

CREATE TABLE IF NOT EXISTS MESSAGE(
ID INT AUTO_INCREMENT,
MESSAGE_ID INT,
MESSAGE VARCHAR(100) NOT NULL,
PRIMARY KEY (ID, MESSAGE_ID)); //


CREATE TRIGGER CHECKS
AFTER INSERT
ON CUSTOMERS1 
FOR EACH ROW
BEGIN
	IF NEW.BIRTH_DATE IS NULL THEN 
		INSERT INTO MESSAGE (MESSAGE_ID, MESSAGE) 
		VALUES(NEW.ID, CONCAT('Hi', NEW.NAME,',Please Update Your date of birth'));
	END IF;
END;//

INSERT INTO CUSTOMERS1 (NAME, EMAIL, BIRTH_DATE) VALUES 
('BALA', 'BALA@GMAIL.COM','6-2-2004'),
('SURIYA', 'SURIYA@GMAILL.COM', '');//

SELECT * FROM MESSAGE;//


## CREATE TRIGER BEFORE UPDATE

CREATE TABLE IF NOT EXISTS EMPLOYEES(
EMP_ID INT PRIMARY KEY,
NAME VARCHAR(40),
AGE INT,
SALARY FLOAT
);//


INSERT INTO EMPLOYEES VALUES (101,'bala', 21, 40000),(102, 'suriya', 22, 45000);//

CREATE TRIGGER SAL
BEFORE UPDATE
ON EMPLOYEES 
FOR EACH ROW
BEGIN 
	IF NEW.SALARY = 100000 THEN SET NEW.SALARY = 85000;
		ELSEIF NEW.SALARY < 100000 THEN SET NEW.SALARY = 75000;
	END IF;
END//

SELECT * FROM EMPLOYEES;//

UPDATE EMPLOYEES SET SALARY = 90000 WHERE EMP_ID = 102;//